#WEB服务配置
server:
  #服务端口号
  port: 8102
  servlet:
#    context-path: /yibot-manage
    session:
      timeout: 30m
  undertow:
    accesslog:
      dir: /data/log/access
      enabled: true
    io-threads: 4
    worker-threads: 64
    buffer-size: 1024
    direct-buffers: true
#数据源配置
spring:
  application:
    name: yibot-manage-node
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy:  org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    generate-ddl: false
    database: mysql
    open-in-view: false
  #缓存配置
  redis:
    host: 192.168.1.167
    port: 16379
  #定时任务配置
  quartz:
    #相关属性配置
    properties:
      org:
        quartz:
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
#分库分表配置
sharding:
  jdbc:
    datasource:
      names: ds-11,ds-21,ds-10051010,ds-default
      ds-11:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://192.168.1.167:3366/yibot_11?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
        username: root
        password: qwertyuiop123
      ds-21:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://192.168.1.167:3366/yibot_21?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
        username: root
        password: qwertyuiop123
      ds-10051010:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://192.168.1.167:3366/yibot_10051010?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
        username: root
        password: qwertyuiop123
      ds-default:
      #系统默认独立数据源
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://192.168.1.167:3366/yibot?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
        username: root
        password: qwertyuiop123
    config:
      sharding:
        #默认分库策略
        #未配置分片规则的表将通过默认数据源定位
        default-data-source-name: ds-default
        default-database-strategy:
          inline:
            sharding-column: appid
            algorithm-expression: ds-${appid}
        #绑定表列表
        binding-tables[0]: t_dialog,t_dialog_detail
        #分库分表配置，可配置多个logic_table_name
        tables:
          t_session:
            actual-data-nodes: ds-${[11,21,10051010]}.t_session_${[201807,201808,201809]}
            database-strategy:
              inline:
                sharding-column: appid
                algorithm-expression: ds-${appid}
            table-strategy:
              inline:
                sharding-column: date_month
                algorithm-expression: t_session_${date_month}
          t_dialog:
            actual-data-nodes: ds-${[11,21,10051010]}.t_dialog_${[201807,201808,201809]}
            database-strategy:
              inline:
                sharding-column: appid
                algorithm-expression: ds-${appid}
            table-strategy:
              inline:
                sharding-column: date_month
                algorithm-expression: t_dialog_${date_month}
          t_dialog_detail:
            actual-data-nodes: ds-${[11,21,10051010]}.t_dialog_detail_${[201807,201808,201809]}
            database-strategy:
              inline:
                sharding-column: appid
                algorithm-expression: ds-${appid}
            table-strategy:
              inline:
                sharding-column: date_month
                algorithm-expression: t_dialog_detail_${date_month}
          t_dialog_answer:
            actual-data-nodes: ds-${[11,21,10051010]}.t_dialog_answer
            database-strategy:
              inline:
                sharding-column: appid
                algorithm-expression: ds-${appid}
          t_city_overview:
            actual-data-nodes: ds-${[11,21,10051010]}.t_city_overview
            database-strategy:
              inline:
                sharding-column: appid
                algorithm-expression: ds-${appid}
          t_judge_overview:
            actual-data-nodes: ds-${[11,21,10051010]}.t_judge_overview
            database-strategy:
              inline:
                sharding-column: appid
                algorithm-expression: ds-${appid}
          t_touch_overview:
            actual-data-nodes: ds-${[11,21,10051010]}.t_touch_overview
            database-strategy:
              inline:
                sharding-column: appid
                algorithm-expression: ds-${appid}
          t_province_overview:
            actual-data-nodes: ds-${[11,21,10051010]}.t_province_overview
            database-strategy:
              inline:
                sharding-column: appid
                algorithm-expression: ds-${appid}
          t_part_trend_overview:
            actual-data-nodes: ds-${[11,21,10051010]}.t_part_trend_overview
            database-strategy:
              inline:
                sharding-column: appid
                algorithm-expression: ds-${appid}
          t_whole_trend_overview:
            actual-data-nodes: ds-${[11,21,10051010]}.t_whole_trend_overview
            database-strategy:
              inline:
                sharding-column: appid
                algorithm-expression: ds-${appid}
          t_whole_service_overview:
            actual-data-nodes: ds-${[11,21,10051010]}.t_whole_service_overview
            database-strategy:
              inline:
                sharding-column: appid
                algorithm-expression: ds-${appid}
          t_faq_touch_overview:
            actual-data-nodes: ds-${[11,21,10051010]}.t_faq_touch_overview
            database-strategy:
              inline:
                sharding-column: appid
                algorithm-expression: ds-${appid}
          t_zrg_overview:
            actual-data-nodes: ds-${[11,21,10051010]}.t_zrg_overview
            database-strategy:
              inline:
                sharding-column: appid
                algorithm-expression: ds-${appid}
          t_hot_faq_overview:
            actual-data-nodes: ds-${[11,21,10051010]}.t_hot_faq_overview
            database-strategy:
              inline:
                sharding-column: appid
                algorithm-expression: ds-${appid}
          t_hot_area_overview:
            actual-data-nodes: ds-${[11,21,10051010]}.t_hot_area_overview
            database-strategy:
              inline:
                sharding-column: appid
                algorithm-expression: ds-${appid}
          t_hot_area_fq_overview:
            actual-data-nodes: ds-${[11,21,10051010]}.t_hot_area_fq_overview
            database-strategy:
              inline:
                sharding-column: appid
                algorithm-expression: ds-${appid}
          t_dialog_back:
            actual-data-nodes: ds-${[11,21,10051010]}.t_dialog_back
            database-strategy:
              inline:
                sharding-column: appid
                algorithm-expression: ds-${appid}
          t_feedback_back:
            actual-data-nodes: ds-${[11,21,10051010]}.t_feedback_back
            database-strategy:
              inline:
                sharding-column: appid
                algorithm-expression: ds-${appid}
        props:
          sql:
            show: false
#      orchestration:
#        name: yibot_ds_sharding
#        overwrite: true
#        zookeeper:
#          namespace: yibot_ds_sharding
#          server-lists: 127.0.0.1:2181
