#WEB服务配置
server:
   port: 8101 #服务端口号
   servlet:
    context-path: /yibot-api
    session:
       timeout: 30m
   undertow:
     accesslog:
       dir: /data/log
       enabled: true
     io-threads: 4
     worker-threads: 64
     buffer-size: 1024
     direct-buffers: true
#数据源配置
spring:
  application:
    name: yibot-api-node1
  jpa:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.MySQL5Dialect
      naming:
        physical-strategy:  org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    generate-ddl: false
    database: mysql
    open-in-view: false
  #缓存配置
  redis:
    host: 192.168.1.167
    port: 16379
#分库分表配置
sharding:
  jdbc:
    datasource:
      names: ds-20771001,ds-10171001,ds-default
      ds-20771001:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://192.168.1.167:3366/yibot_20771001?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
        username: root
        password: qwertyuiop123
        minimum-idle: 1
        maximum-pool-size: 30
        auto-commit: true
        idle-timeout: 60000
        max-lifetime: 1800000
        connection-test-query: SELECT 1
        connection-timeout: 60000
      ds-10171001:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://192.168.1.167:3366/yibot_10171001?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
        username: root
        password: qwertyuiop123
        minimum-idle: 1
        maximum-pool-size: 30
        auto-commit: true
        idle-timeout: 60000
        max-lifetime: 1800000
        connection-timeout: 60000
      ds-default:
      #系统默认独立数据源
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://192.168.1.167:3366/yibot?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
        username: root
        password: qwertyuiop123
        minimum-idle: 1
        maximum-pool-size: 30
        auto-commit: true
        idle-timeout: 60000
        max-lifetime: 1800000
        connection-timeout: 60000
    config:
      sharding:
        #默认分库策略
        #未配置分片规则的表将通过默认数据源定位
        default-data-source-name: ds-default
        default-database-strategy:
          inline:
            sharding-column: appid
            algorithm-expression: ds-${appid}
        #绑定表列表
        binding-tables[0]: t_dialog,t_dialog_detail
        #分库分表配置，可配置多个logic_table_name
        tables:
          t_session:
            actual-data-nodes: ds-${[20771001,10171001]}.t_session_${[201807]}
            database-strategy:
              inline:
                sharding-column: appid
                algorithm-expression: ds-${appid}
            table-strategy:
              inline:
                sharding-column: date_month
                algorithm-expression: t_session_${date_month}
          t_dialog:
            actual-data-nodes: ds-${[20771001,10171001]}.t_dialog_${[201807]}
            database-strategy:
              inline:
                sharding-column: appid
                algorithm-expression: ds-${appid}
            table-strategy:
              inline:
                sharding-column: date_month
                algorithm-expression: t_dialog_${date_month}
          t_dialog_detail:
            actual-data-nodes: ds-${[20771001,10171001]}.t_dialog_detail_${[201807]}
            database-strategy:
              inline:
                sharding-column: appid
                algorithm-expression: ds-${appid}
            table-strategy:
              inline:
                sharding-column: date_month
                algorithm-expression: t_dialog_detail_${date_month}
          t_dialog_answer:
            actual-data-nodes: ds-${[20771001,10171001]}.t_dialog_answer
            database-strategy:
              inline:
                sharding-column: appid
                algorithm-expression: ds-${appid}
          t_city_overview:
            actual-data-nodes: ds-${[20771001,10171001]}.t_city_overview
            database-strategy:
              inline:
                sharding-column: appid
                algorithm-expression: ds-${appid}
            key-generator-column-name: id
          t_judge_overview:
            actual-data-nodes: ds-${[20771001,10171001]}.t_judge_overview
            database-strategy:
              inline:
                sharding-column: appid
                algorithm-expression: ds-${appid}
            key-generator-column-name: id
          t_touch_overview:
            actual-data-nodes: ds-${[20771001,10171001]}.t_touch_overview
            database-strategy:
              inline:
                sharding-column: appid
                algorithm-expression: ds-${appid}
            key-generator-column-name: id
          t_province_overview:
            actual-data-nodes: ds-${[20771001,10171001]}.t_province_overview
            database-strategy:
              inline:
                sharding-column: appid
                algorithm-expression: ds-${appid}
            key-generator-column-name: id
          t_part_trend_overview:
            actual-data-nodes: ds-${[20771001,10171001]}.t_part_trend_overview
            database-strategy:
              inline:
                sharding-column: appid
                algorithm-expression: ds-${appid}
            key-generator-column-name: id
          t_whole_trend_overview:
            actual-data-nodes: ds-${[20771001,10171001]}.t_whole_trend_overview
            database-strategy:
              inline:
                sharding-column: appid
                algorithm-expression: ds-${appid}
            key-generator-column-name: id
          t_faq_touch_overview:
            actual-data-nodes: ds-${[20771001,10171001]}.t_faq_touch_overview
            database-strategy:
              inline:
                sharding-column: appid
                algorithm-expression: ds-${appid}
            key-generator-column-name: id
          t_zrg_overview:
            actual-data-nodes: ds-${[20771001,10171001]}.t_zrg_overview
            database-strategy:
              inline:
                sharding-column: appid
                algorithm-expression: ds-${appid}
            key-generator-column-name: id
          t_hot_faq_overview:
            actual-data-nodes: ds-${[20771001,10171001]}.t_hot_faq_overview
            database-strategy:
              inline:
                sharding-column: appid
                algorithm-expression: ds-${appid}
            key-generator-column-name: id
          t_hot_area_overview:
            actual-data-nodes: ds-${[20771001,10171001]}.t_hot_area_overview
            database-strategy:
              inline:
                sharding-column: appid
                algorithm-expression: ds-${appid}
            key-generator-column-name: id
          t_hot_area_fq_overview:
            actual-data-nodes: ds-${[20771001,10171001]}.t_hot_area_fq_overview
            database-strategy:
              inline:
                sharding-column: appid
                algorithm-expression: ds-${appid}
            key-generator-column-name: id
          t_dialog_back:
            actual-data-nodes: ds-${[20771001,10171001]}.t_dialog_back
            database-strategy:
              inline:
                sharding-column: appid
                algorithm-expression: ds-${appid}
            key-generator-column-name: id
          t_feedback_back:
            actual-data-nodes: ds-${[20771001,10171001]}.t_feedback_back
            database-strategy:
              inline:
                sharding-column: appid
                algorithm-expression: ds-${appid}
            key-generator-column-name: id
        props:
          sql:
            show: true
#      orchestration:
#        name: yibot_ds_sharding
#        overwrite: true
#        zookeeper:
#          namespace: yibot_ds_sharding
#          server-lists: 127.0.0.1:2181

#自定义属性
yibot:
  oldServiceUrl: http://10.3.1.3:5000/
