/*
 * This file is generated by jOOQ.
 */
package com.zhuiyi.model.jooq;


import com.zhuiyi.model.jooq.tables.*;
import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;

import javax.annotation.Generated;


/**
 * A class modelling indexes of tables of the <code>yibot</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index T_CITY_OVERVIEW_IDX_DS_IT = Indexes0.T_CITY_OVERVIEW_IDX_DS_IT;
    public static final Index T_CITY_OVERVIEW_PRIMARY = Indexes0.T_CITY_OVERVIEW_PRIMARY;
    public static final Index T_DIALOG_IDX_DATE_SIGN = Indexes0.T_DIALOG_IDX_DATE_SIGN;
    public static final Index T_DIALOG_PRIMARY = Indexes0.T_DIALOG_PRIMARY;
    public static final Index T_DIALOG_BACK_IDX_EXACT_TIME = Indexes0.T_DIALOG_BACK_IDX_EXACT_TIME;
    public static final Index T_DIALOG_BACK_PRIMARY = Indexes0.T_DIALOG_BACK_PRIMARY;
    public static final Index T_DIALOG_DETAIL_PRIMARY = Indexes0.T_DIALOG_DETAIL_PRIMARY;
    public static final Index T_FAQ_TOUCH_OVERVIEW_IDX_DS_FI = Indexes0.T_FAQ_TOUCH_OVERVIEW_IDX_DS_FI;
    public static final Index T_FAQ_TOUCH_OVERVIEW_PRIMARY = Indexes0.T_FAQ_TOUCH_OVERVIEW_PRIMARY;
    public static final Index T_FEEDBACK_BACK_IDX_EXACT_TIME = Indexes0.T_FEEDBACK_BACK_IDX_EXACT_TIME;
    public static final Index T_FEEDBACK_BACK_PRIMARY = Indexes0.T_FEEDBACK_BACK_PRIMARY;
    public static final Index T_HOT_AREA_FQ_OVERVIEW_PRIMARY = Indexes0.T_HOT_AREA_FQ_OVERVIEW_PRIMARY;
    public static final Index T_HOT_AREA_OVERVIEW_PRIMARY = Indexes0.T_HOT_AREA_OVERVIEW_PRIMARY;
    public static final Index T_HOT_FAQ_OVERVIEW_IDX_DS_IT = Indexes0.T_HOT_FAQ_OVERVIEW_IDX_DS_IT;
    public static final Index T_HOT_FAQ_OVERVIEW_PRIMARY = Indexes0.T_HOT_FAQ_OVERVIEW_PRIMARY;
    public static final Index T_JUDGE_OVERVIEW_IDX_DS_IT = Indexes0.T_JUDGE_OVERVIEW_IDX_DS_IT;
    public static final Index T_JUDGE_OVERVIEW_PRIMARY = Indexes0.T_JUDGE_OVERVIEW_PRIMARY;
    public static final Index T_PART_TREND_OVERVIEW_IDX_DS_IT = Indexes0.T_PART_TREND_OVERVIEW_IDX_DS_IT;
    public static final Index T_PART_TREND_OVERVIEW_PRIMARY = Indexes0.T_PART_TREND_OVERVIEW_PRIMARY;
    public static final Index T_PROVINCE_OVERVIEW_IDX_DS_IT = Indexes0.T_PROVINCE_OVERVIEW_IDX_DS_IT;
    public static final Index T_PROVINCE_OVERVIEW_PRIMARY = Indexes0.T_PROVINCE_OVERVIEW_PRIMARY;
    public static final Index T_SESSION_IDX_ACCOUNT = Indexes0.T_SESSION_IDX_ACCOUNT;
    public static final Index T_SESSION_IDX_DATE_SIGN = Indexes0.T_SESSION_IDX_DATE_SIGN;
    public static final Index T_SESSION_IDX_ST_SO_RN = Indexes0.T_SESSION_IDX_ST_SO_RN;
    public static final Index T_SESSION_PRIMARY = Indexes0.T_SESSION_PRIMARY;
    public static final Index T_TOUCH_OVERVIEW_IDX_DS_IT = Indexes0.T_TOUCH_OVERVIEW_IDX_DS_IT;
    public static final Index T_TOUCH_OVERVIEW_PRIMARY = Indexes0.T_TOUCH_OVERVIEW_PRIMARY;
    public static final Index T_WHOLE_TREND_OVERVIEW_IDX_DS_IT = Indexes0.T_WHOLE_TREND_OVERVIEW_IDX_DS_IT;
    public static final Index T_WHOLE_TREND_OVERVIEW_PRIMARY = Indexes0.T_WHOLE_TREND_OVERVIEW_PRIMARY;
    public static final Index T_ZRG_OVERVIEW_IDX_DS_IT = Indexes0.T_ZRG_OVERVIEW_IDX_DS_IT;
    public static final Index T_ZRG_OVERVIEW_PRIMARY = Indexes0.T_ZRG_OVERVIEW_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index T_CITY_OVERVIEW_IDX_DS_IT = Internal.createIndex("idx_ds_it", TCityOverview.T_CITY_OVERVIEW, new OrderField[] { TCityOverview.T_CITY_OVERVIEW.DATE_SIGN, TCityOverview.T_CITY_OVERVIEW.IS_TOTAL }, false);
        public static Index T_CITY_OVERVIEW_PRIMARY = Internal.createIndex("PRIMARY", TCityOverview.T_CITY_OVERVIEW, new OrderField[] { TCityOverview.T_CITY_OVERVIEW.ID, TCityOverview.T_CITY_OVERVIEW.APPID }, true);
        public static Index T_DIALOG_IDX_DATE_SIGN = Internal.createIndex("idx_date_sign", TDialog.T_DIALOG, new OrderField[] { TDialog.T_DIALOG.DATE_SIGN }, false);
        public static Index T_DIALOG_PRIMARY = Internal.createIndex("PRIMARY", TDialog.T_DIALOG, new OrderField[] { TDialog.T_DIALOG.ID, TDialog.T_DIALOG.EXACT_TIME, TDialog.T_DIALOG.APPID, TDialog.T_DIALOG.DATE_MONTH }, true);
        public static Index T_DIALOG_BACK_IDX_EXACT_TIME = Internal.createIndex("idx_exact_time", TDialogBack.T_DIALOG_BACK, new OrderField[] { TDialogBack.T_DIALOG_BACK.EXACT_TIME }, false);
        public static Index T_DIALOG_BACK_PRIMARY = Internal.createIndex("PRIMARY", TDialogBack.T_DIALOG_BACK, new OrderField[] { TDialogBack.T_DIALOG_BACK.ID, TDialogBack.T_DIALOG_BACK.APPID }, true);
        public static Index T_DIALOG_DETAIL_PRIMARY = Internal.createIndex("PRIMARY", TDialogDetail.T_DIALOG_DETAIL, new OrderField[] { TDialogDetail.T_DIALOG_DETAIL.ID, TDialogDetail.T_DIALOG_DETAIL.APPID, TDialogDetail.T_DIALOG_DETAIL.EXACT_TIME, TDialogDetail.T_DIALOG_DETAIL.DATE_MONTH }, true);
        public static Index T_FAQ_TOUCH_OVERVIEW_IDX_DS_FI = Internal.createIndex("idx_ds_fi", TFaqTouchOverview.T_FAQ_TOUCH_OVERVIEW, new OrderField[] { TFaqTouchOverview.T_FAQ_TOUCH_OVERVIEW.DATE_SIGN, TFaqTouchOverview.T_FAQ_TOUCH_OVERVIEW.FAQ_ID }, false);
        public static Index T_FAQ_TOUCH_OVERVIEW_PRIMARY = Internal.createIndex("PRIMARY", TFaqTouchOverview.T_FAQ_TOUCH_OVERVIEW, new OrderField[] { TFaqTouchOverview.T_FAQ_TOUCH_OVERVIEW.ID, TFaqTouchOverview.T_FAQ_TOUCH_OVERVIEW.APPID }, true);
        public static Index T_FEEDBACK_BACK_IDX_EXACT_TIME = Internal.createIndex("idx_exact_time", TFeedbackBack.T_FEEDBACK_BACK, new OrderField[] { TFeedbackBack.T_FEEDBACK_BACK.EXACT_TIME }, false);
        public static Index T_FEEDBACK_BACK_PRIMARY = Internal.createIndex("PRIMARY", TFeedbackBack.T_FEEDBACK_BACK, new OrderField[] { TFeedbackBack.T_FEEDBACK_BACK.ID, TFeedbackBack.T_FEEDBACK_BACK.APPID }, true);
        public static Index T_HOT_AREA_FQ_OVERVIEW_PRIMARY = Internal.createIndex("PRIMARY", THotAreaFqOverview.T_HOT_AREA_FQ_OVERVIEW, new OrderField[] { THotAreaFqOverview.T_HOT_AREA_FQ_OVERVIEW.ID, THotAreaFqOverview.T_HOT_AREA_FQ_OVERVIEW.APPID }, true);
        public static Index T_HOT_AREA_OVERVIEW_PRIMARY = Internal.createIndex("PRIMARY", THotAreaOverview.T_HOT_AREA_OVERVIEW, new OrderField[] { THotAreaOverview.T_HOT_AREA_OVERVIEW.ID, THotAreaOverview.T_HOT_AREA_OVERVIEW.APPID }, true);
        public static Index T_HOT_FAQ_OVERVIEW_IDX_DS_IT = Internal.createIndex("idx_ds_it", THotFaqOverview.T_HOT_FAQ_OVERVIEW, new OrderField[] { THotFaqOverview.T_HOT_FAQ_OVERVIEW.DATE_SIGN, THotFaqOverview.T_HOT_FAQ_OVERVIEW.FAQ_ID }, false);
        public static Index T_HOT_FAQ_OVERVIEW_PRIMARY = Internal.createIndex("PRIMARY", THotFaqOverview.T_HOT_FAQ_OVERVIEW, new OrderField[] { THotFaqOverview.T_HOT_FAQ_OVERVIEW.ID, THotFaqOverview.T_HOT_FAQ_OVERVIEW.APPID }, true);
        public static Index T_JUDGE_OVERVIEW_IDX_DS_IT = Internal.createIndex("idx_ds_it", TJudgeOverview.T_JUDGE_OVERVIEW, new OrderField[] { TJudgeOverview.T_JUDGE_OVERVIEW.DATE_SIGN, TJudgeOverview.T_JUDGE_OVERVIEW.IS_TOTAL }, false);
        public static Index T_JUDGE_OVERVIEW_PRIMARY = Internal.createIndex("PRIMARY", TJudgeOverview.T_JUDGE_OVERVIEW, new OrderField[] { TJudgeOverview.T_JUDGE_OVERVIEW.ID, TJudgeOverview.T_JUDGE_OVERVIEW.APPID }, true);
        public static Index T_PART_TREND_OVERVIEW_IDX_DS_IT = Internal.createIndex("idx_ds_it", TPartTrendOverview.T_PART_TREND_OVERVIEW, new OrderField[] { TPartTrendOverview.T_PART_TREND_OVERVIEW.DATE_SIGN, TPartTrendOverview.T_PART_TREND_OVERVIEW.IS_TOTAL }, false);
        public static Index T_PART_TREND_OVERVIEW_PRIMARY = Internal.createIndex("PRIMARY", TPartTrendOverview.T_PART_TREND_OVERVIEW, new OrderField[] { TPartTrendOverview.T_PART_TREND_OVERVIEW.ID, TPartTrendOverview.T_PART_TREND_OVERVIEW.APPID }, true);
        public static Index T_PROVINCE_OVERVIEW_IDX_DS_IT = Internal.createIndex("idx_ds_it", TProvinceOverview.T_PROVINCE_OVERVIEW, new OrderField[] { TProvinceOverview.T_PROVINCE_OVERVIEW.DATE_SIGN, TProvinceOverview.T_PROVINCE_OVERVIEW.IS_TOTAL }, false);
        public static Index T_PROVINCE_OVERVIEW_PRIMARY = Internal.createIndex("PRIMARY", TProvinceOverview.T_PROVINCE_OVERVIEW, new OrderField[] { TProvinceOverview.T_PROVINCE_OVERVIEW.ID, TProvinceOverview.T_PROVINCE_OVERVIEW.APPID }, true);
        public static Index T_SESSION_IDX_ACCOUNT = Internal.createIndex("idx_account", TSession.T_SESSION, new OrderField[] { TSession.T_SESSION.ACCOUNT }, false);
        public static Index T_SESSION_IDX_DATE_SIGN = Internal.createIndex("idx_date_sign", TSession.T_SESSION, new OrderField[] { TSession.T_SESSION.DATE_SIGN }, false);
        public static Index T_SESSION_IDX_ST_SO_RN = Internal.createIndex("idx_st_so_rn", TSession.T_SESSION, new OrderField[] { TSession.T_SESSION.START_TIME, TSession.T_SESSION.ROUND_NUM, TSession.T_SESSION.SOURCE }, false);
        public static Index T_SESSION_PRIMARY = Internal.createIndex("PRIMARY", TSession.T_SESSION, new OrderField[] { TSession.T_SESSION.ID, TSession.T_SESSION.START_TIME, TSession.T_SESSION.APPID, TSession.T_SESSION.DATE_MONTH }, true);
        public static Index T_TOUCH_OVERVIEW_IDX_DS_IT = Internal.createIndex("idx_ds_it", TTouchOverview.T_TOUCH_OVERVIEW, new OrderField[] { TTouchOverview.T_TOUCH_OVERVIEW.DATE_SIGN, TTouchOverview.T_TOUCH_OVERVIEW.IS_TOTAL }, false);
        public static Index T_TOUCH_OVERVIEW_PRIMARY = Internal.createIndex("PRIMARY", TTouchOverview.T_TOUCH_OVERVIEW, new OrderField[] { TTouchOverview.T_TOUCH_OVERVIEW.ID, TTouchOverview.T_TOUCH_OVERVIEW.APPID }, true);
        public static Index T_WHOLE_TREND_OVERVIEW_IDX_DS_IT = Internal.createIndex("idx_ds_it", TWholeTrendOverview.T_WHOLE_TREND_OVERVIEW, new OrderField[] { TWholeTrendOverview.T_WHOLE_TREND_OVERVIEW.DATE_SIGN, TWholeTrendOverview.T_WHOLE_TREND_OVERVIEW.IS_TOTAL }, false);
        public static Index T_WHOLE_TREND_OVERVIEW_PRIMARY = Internal.createIndex("PRIMARY", TWholeTrendOverview.T_WHOLE_TREND_OVERVIEW, new OrderField[] { TWholeTrendOverview.T_WHOLE_TREND_OVERVIEW.ID, TWholeTrendOverview.T_WHOLE_TREND_OVERVIEW.APPID }, true);
        public static Index T_ZRG_OVERVIEW_IDX_DS_IT = Internal.createIndex("idx_ds_it", TZrgOverview.T_ZRG_OVERVIEW, new OrderField[] { TZrgOverview.T_ZRG_OVERVIEW.DATE_SIGN, TZrgOverview.T_ZRG_OVERVIEW.IS_TOTAL }, false);
        public static Index T_ZRG_OVERVIEW_PRIMARY = Internal.createIndex("PRIMARY", TZrgOverview.T_ZRG_OVERVIEW, new OrderField[] { TZrgOverview.T_ZRG_OVERVIEW.ID, TZrgOverview.T_ZRG_OVERVIEW.APPID }, true);
    }
}
