/*
 * This file is generated by jOOQ.
 */
package com.zhuiyi.model.jooq;


import com.zhuiyi.model.jooq.tables.*;
import com.zhuiyi.model.jooq.tables.records.*;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;

import javax.annotation.Generated;


/**
 * A class modelling foreign key relationships and constraints of tables of
 * the <code>yibot</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<TCityOverviewRecord> KEY_T_CITY_OVERVIEW_PRIMARY = UniqueKeys0.KEY_T_CITY_OVERVIEW_PRIMARY;
    public static final UniqueKey<TDialogRecord> KEY_T_DIALOG_PRIMARY = UniqueKeys0.KEY_T_DIALOG_PRIMARY;
    public static final UniqueKey<TDialogBackRecord> KEY_T_DIALOG_BACK_PRIMARY = UniqueKeys0.KEY_T_DIALOG_BACK_PRIMARY;
    public static final UniqueKey<TDialogDetailRecord> KEY_T_DIALOG_DETAIL_PRIMARY = UniqueKeys0.KEY_T_DIALOG_DETAIL_PRIMARY;
    public static final UniqueKey<TFaqTouchOverviewRecord> KEY_T_FAQ_TOUCH_OVERVIEW_PRIMARY = UniqueKeys0.KEY_T_FAQ_TOUCH_OVERVIEW_PRIMARY;
    public static final UniqueKey<TFeedbackBackRecord> KEY_T_FEEDBACK_BACK_PRIMARY = UniqueKeys0.KEY_T_FEEDBACK_BACK_PRIMARY;
    public static final UniqueKey<THotAreaFqOverviewRecord> KEY_T_HOT_AREA_FQ_OVERVIEW_PRIMARY = UniqueKeys0.KEY_T_HOT_AREA_FQ_OVERVIEW_PRIMARY;
    public static final UniqueKey<THotAreaOverviewRecord> KEY_T_HOT_AREA_OVERVIEW_PRIMARY = UniqueKeys0.KEY_T_HOT_AREA_OVERVIEW_PRIMARY;
    public static final UniqueKey<THotFaqOverviewRecord> KEY_T_HOT_FAQ_OVERVIEW_PRIMARY = UniqueKeys0.KEY_T_HOT_FAQ_OVERVIEW_PRIMARY;
    public static final UniqueKey<TJudgeOverviewRecord> KEY_T_JUDGE_OVERVIEW_PRIMARY = UniqueKeys0.KEY_T_JUDGE_OVERVIEW_PRIMARY;
    public static final UniqueKey<TPartTrendOverviewRecord> KEY_T_PART_TREND_OVERVIEW_PRIMARY = UniqueKeys0.KEY_T_PART_TREND_OVERVIEW_PRIMARY;
    public static final UniqueKey<TProvinceOverviewRecord> KEY_T_PROVINCE_OVERVIEW_PRIMARY = UniqueKeys0.KEY_T_PROVINCE_OVERVIEW_PRIMARY;
    public static final UniqueKey<TSessionRecord> KEY_T_SESSION_PRIMARY = UniqueKeys0.KEY_T_SESSION_PRIMARY;
    public static final UniqueKey<TTouchOverviewRecord> KEY_T_TOUCH_OVERVIEW_PRIMARY = UniqueKeys0.KEY_T_TOUCH_OVERVIEW_PRIMARY;
    public static final UniqueKey<TWholeTrendOverviewRecord> KEY_T_WHOLE_TREND_OVERVIEW_PRIMARY = UniqueKeys0.KEY_T_WHOLE_TREND_OVERVIEW_PRIMARY;
    public static final UniqueKey<TZrgOverviewRecord> KEY_T_ZRG_OVERVIEW_PRIMARY = UniqueKeys0.KEY_T_ZRG_OVERVIEW_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<TCityOverviewRecord> KEY_T_CITY_OVERVIEW_PRIMARY = Internal.createUniqueKey(TCityOverview.T_CITY_OVERVIEW, "KEY_t_city_overview_PRIMARY", TCityOverview.T_CITY_OVERVIEW.ID, TCityOverview.T_CITY_OVERVIEW.APPID);
        public static final UniqueKey<TDialogRecord> KEY_T_DIALOG_PRIMARY = Internal.createUniqueKey(TDialog.T_DIALOG, "KEY_t_dialog_PRIMARY", TDialog.T_DIALOG.ID, TDialog.T_DIALOG.EXACT_TIME, TDialog.T_DIALOG.APPID, TDialog.T_DIALOG.DATE_MONTH);
        public static final UniqueKey<TDialogBackRecord> KEY_T_DIALOG_BACK_PRIMARY = Internal.createUniqueKey(TDialogBack.T_DIALOG_BACK, "KEY_t_dialog_back_PRIMARY", TDialogBack.T_DIALOG_BACK.ID, TDialogBack.T_DIALOG_BACK.APPID);
        public static final UniqueKey<TDialogDetailRecord> KEY_T_DIALOG_DETAIL_PRIMARY = Internal.createUniqueKey(TDialogDetail.T_DIALOG_DETAIL, "KEY_t_dialog_detail_PRIMARY", TDialogDetail.T_DIALOG_DETAIL.ID, TDialogDetail.T_DIALOG_DETAIL.APPID, TDialogDetail.T_DIALOG_DETAIL.EXACT_TIME, TDialogDetail.T_DIALOG_DETAIL.DATE_MONTH);
        public static final UniqueKey<TFaqTouchOverviewRecord> KEY_T_FAQ_TOUCH_OVERVIEW_PRIMARY = Internal.createUniqueKey(TFaqTouchOverview.T_FAQ_TOUCH_OVERVIEW, "KEY_t_faq_touch_overview_PRIMARY", TFaqTouchOverview.T_FAQ_TOUCH_OVERVIEW.ID, TFaqTouchOverview.T_FAQ_TOUCH_OVERVIEW.APPID);
        public static final UniqueKey<TFeedbackBackRecord> KEY_T_FEEDBACK_BACK_PRIMARY = Internal.createUniqueKey(TFeedbackBack.T_FEEDBACK_BACK, "KEY_t_feedback_back_PRIMARY", TFeedbackBack.T_FEEDBACK_BACK.ID, TFeedbackBack.T_FEEDBACK_BACK.APPID);
        public static final UniqueKey<THotAreaFqOverviewRecord> KEY_T_HOT_AREA_FQ_OVERVIEW_PRIMARY = Internal.createUniqueKey(THotAreaFqOverview.T_HOT_AREA_FQ_OVERVIEW, "KEY_t_hot_area_fq_overview_PRIMARY", THotAreaFqOverview.T_HOT_AREA_FQ_OVERVIEW.ID, THotAreaFqOverview.T_HOT_AREA_FQ_OVERVIEW.APPID);
        public static final UniqueKey<THotAreaOverviewRecord> KEY_T_HOT_AREA_OVERVIEW_PRIMARY = Internal.createUniqueKey(THotAreaOverview.T_HOT_AREA_OVERVIEW, "KEY_t_hot_area_overview_PRIMARY", THotAreaOverview.T_HOT_AREA_OVERVIEW.ID, THotAreaOverview.T_HOT_AREA_OVERVIEW.APPID);
        public static final UniqueKey<THotFaqOverviewRecord> KEY_T_HOT_FAQ_OVERVIEW_PRIMARY = Internal.createUniqueKey(THotFaqOverview.T_HOT_FAQ_OVERVIEW, "KEY_t_hot_faq_overview_PRIMARY", THotFaqOverview.T_HOT_FAQ_OVERVIEW.ID, THotFaqOverview.T_HOT_FAQ_OVERVIEW.APPID);
        public static final UniqueKey<TJudgeOverviewRecord> KEY_T_JUDGE_OVERVIEW_PRIMARY = Internal.createUniqueKey(TJudgeOverview.T_JUDGE_OVERVIEW, "KEY_t_judge_overview_PRIMARY", TJudgeOverview.T_JUDGE_OVERVIEW.ID, TJudgeOverview.T_JUDGE_OVERVIEW.APPID);
        public static final UniqueKey<TPartTrendOverviewRecord> KEY_T_PART_TREND_OVERVIEW_PRIMARY = Internal.createUniqueKey(TPartTrendOverview.T_PART_TREND_OVERVIEW, "KEY_t_part_trend_overview_PRIMARY", TPartTrendOverview.T_PART_TREND_OVERVIEW.ID, TPartTrendOverview.T_PART_TREND_OVERVIEW.APPID);
        public static final UniqueKey<TProvinceOverviewRecord> KEY_T_PROVINCE_OVERVIEW_PRIMARY = Internal.createUniqueKey(TProvinceOverview.T_PROVINCE_OVERVIEW, "KEY_t_province_overview_PRIMARY", TProvinceOverview.T_PROVINCE_OVERVIEW.ID, TProvinceOverview.T_PROVINCE_OVERVIEW.APPID);
        public static final UniqueKey<TSessionRecord> KEY_T_SESSION_PRIMARY = Internal.createUniqueKey(TSession.T_SESSION, "KEY_t_session_PRIMARY", TSession.T_SESSION.ID, TSession.T_SESSION.START_TIME, TSession.T_SESSION.APPID, TSession.T_SESSION.DATE_MONTH);
        public static final UniqueKey<TTouchOverviewRecord> KEY_T_TOUCH_OVERVIEW_PRIMARY = Internal.createUniqueKey(TTouchOverview.T_TOUCH_OVERVIEW, "KEY_t_touch_overview_PRIMARY", TTouchOverview.T_TOUCH_OVERVIEW.ID, TTouchOverview.T_TOUCH_OVERVIEW.APPID);
        public static final UniqueKey<TWholeTrendOverviewRecord> KEY_T_WHOLE_TREND_OVERVIEW_PRIMARY = Internal.createUniqueKey(TWholeTrendOverview.T_WHOLE_TREND_OVERVIEW, "KEY_t_whole_trend_overview_PRIMARY", TWholeTrendOverview.T_WHOLE_TREND_OVERVIEW.ID, TWholeTrendOverview.T_WHOLE_TREND_OVERVIEW.APPID);
        public static final UniqueKey<TZrgOverviewRecord> KEY_T_ZRG_OVERVIEW_PRIMARY = Internal.createUniqueKey(TZrgOverview.T_ZRG_OVERVIEW, "KEY_t_zrg_overview_PRIMARY", TZrgOverview.T_ZRG_OVERVIEW.ID, TZrgOverview.T_ZRG_OVERVIEW.APPID);
    }
}
