/*
 * This file is generated by jOOQ.
 */
package com.zhuiyi.model.jooq;


import com.zhuiyi.model.jooq.tables.*;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;
import org.jooq.meta.firebird.rdb.DefaultCatalog;

import javax.annotation.Generated;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Yibot extends SchemaImpl {

    private static final long serialVersionUID = -1478045201;

    /**
     * The reference instance of <code>yibot</code>
     */
    public static final Yibot YIBOT = new Yibot();

    /**
     * 各城市faq数据统计表
     */
    public final TCityOverview T_CITY_OVERVIEW = TCityOverview.T_CITY_OVERVIEW;

    /**
     * 机器对话流水表
     */
    public final TDialog T_DIALOG = TDialog.T_DIALOG;

    /**
     * 原始dialog数据记录表
     */
    public final TDialogBack T_DIALOG_BACK = TDialogBack.T_DIALOG_BACK;

    /**
     * 机器对话流水明细表
     */
    public final TDialogDetail T_DIALOG_DETAIL = TDialogDetail.T_DIALOG_DETAIL;

    /**
     * faq触达数据统计表
     */
    public final TFaqTouchOverview T_FAQ_TOUCH_OVERVIEW = TFaqTouchOverview.T_FAQ_TOUCH_OVERVIEW;

    /**
     * 原始feedback数据记录表
     */
    public final TFeedbackBack T_FEEDBACK_BACK = TFeedbackBack.T_FEEDBACK_BACK;

    /**
     * 热点区域FAQ数据统计表
     */
    public final THotAreaFqOverview T_HOT_AREA_FQ_OVERVIEW = THotAreaFqOverview.T_HOT_AREA_FQ_OVERVIEW;

    /**
     * 热点区域数据统计表
     */
    public final THotAreaOverview T_HOT_AREA_OVERVIEW = THotAreaOverview.T_HOT_AREA_OVERVIEW;

    /**
     * 热点FAQ数据统计表
     */
    public final THotFaqOverview T_HOT_FAQ_OVERVIEW = THotFaqOverview.T_HOT_FAQ_OVERVIEW;

    /**
     * 用户评价统计表
     */
    public final TJudgeOverview T_JUDGE_OVERVIEW = TJudgeOverview.T_JUDGE_OVERVIEW;

    /**
     * 耗时和访问量趋势统计表
     */
    public final TPartTrendOverview T_PART_TREND_OVERVIEW = TPartTrendOverview.T_PART_TREND_OVERVIEW;

    /**
     * 各省faq数据热点分析统计表
     */
    public final TProvinceOverview T_PROVINCE_OVERVIEW = TProvinceOverview.T_PROVINCE_OVERVIEW;

    /**
     * 会话表
     */
    public final TSession T_SESSION = TSession.T_SESSION;

    /**
     * FAQ触达率数据统计表
     */
    public final TTouchOverview T_TOUCH_OVERVIEW = TTouchOverview.T_TOUCH_OVERVIEW;

    /**
     * 整体趋势统计表
     */
    public final TWholeTrendOverview T_WHOLE_TREND_OVERVIEW = TWholeTrendOverview.T_WHOLE_TREND_OVERVIEW;

    /**
     * 转人工数据统计表
     */
    public final TZrgOverview T_ZRG_OVERVIEW = TZrgOverview.T_ZRG_OVERVIEW;

    /**
     * No further instances allowed
     */
    private Yibot() {
        super("", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            TCityOverview.T_CITY_OVERVIEW,
            TDialog.T_DIALOG,
            TDialogBack.T_DIALOG_BACK,
            TDialogDetail.T_DIALOG_DETAIL,
            TFaqTouchOverview.T_FAQ_TOUCH_OVERVIEW,
            TFeedbackBack.T_FEEDBACK_BACK,
            THotAreaFqOverview.T_HOT_AREA_FQ_OVERVIEW,
            THotAreaOverview.T_HOT_AREA_OVERVIEW,
            THotFaqOverview.T_HOT_FAQ_OVERVIEW,
            TJudgeOverview.T_JUDGE_OVERVIEW,
            TPartTrendOverview.T_PART_TREND_OVERVIEW,
            TProvinceOverview.T_PROVINCE_OVERVIEW,
            TSession.T_SESSION,
            TTouchOverview.T_TOUCH_OVERVIEW,
            TWholeTrendOverview.T_WHOLE_TREND_OVERVIEW,
            TZrgOverview.T_ZRG_OVERVIEW);
    }
}
