/*
 * This file is generated by jOOQ.
 */
package com.zhuiyi.model.jooq.tables;


import com.zhuiyi.model.jooq.Indexes;
import com.zhuiyi.model.jooq.Keys;
import com.zhuiyi.model.jooq.Yibot;
import com.zhuiyi.model.jooq.tables.records.TCityOverviewRecord;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;

import javax.annotation.Generated;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;


/**
 * 各城市faq数据统计表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TCityOverview extends TableImpl<TCityOverviewRecord> {

    private static final long serialVersionUID = 1662921801;

    /**
     * The reference instance of <code>yibot.t_city_overview</code>
     */
    public static final TCityOverview T_CITY_OVERVIEW = new TCityOverview();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TCityOverviewRecord> getRecordType() {
        return TCityOverviewRecord.class;
    }

    /**
     * The column <code>yibot.t_city_overview.id</code>.
     */
    public final TableField<TCityOverviewRecord, ULong> ID = createField("id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>yibot.t_city_overview.appid</code>.
     */
    public final TableField<TCityOverviewRecord, String> APPID = createField("appid", org.jooq.impl.SQLDataType.VARCHAR(30).nullable(false), this, "");

    /**
     * The column <code>yibot.t_city_overview.date_sign</code>.
     */
    public final TableField<TCityOverviewRecord, String> DATE_SIGN = createField("date_sign", org.jooq.impl.SQLDataType.CHAR(10).nullable(false), this, "");

    /**
     * The column <code>yibot.t_city_overview.is_total</code>.
     */
    public final TableField<TCityOverviewRecord, Boolean> IS_TOTAL = createField("is_total", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>yibot.t_city_overview.cid</code>.
     */
    public final TableField<TCityOverviewRecord, String> CID = createField("cid", org.jooq.impl.SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>yibot.t_city_overview.client</code>.
     */
    public final TableField<TCityOverviewRecord, String> CLIENT = createField("client", org.jooq.impl.SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>yibot.t_city_overview.eid</code>.
     */
    public final TableField<TCityOverviewRecord, String> EID = createField("eid", org.jooq.impl.SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>yibot.t_city_overview.lables</code>.
     */
    public final TableField<TCityOverviewRecord, String> LABLES = createField("lables", org.jooq.impl.SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>yibot.t_city_overview.im</code>.
     */
    public final TableField<TCityOverviewRecord, String> IM = createField("im", org.jooq.impl.SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>yibot.t_city_overview.gmt_create</code>.
     */
    public final TableField<TCityOverviewRecord, Timestamp> GMT_CREATE = createField("gmt_create", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>yibot.t_city_overview.gmt_modified</code>.
     */
    public final TableField<TCityOverviewRecord, Timestamp> GMT_MODIFIED = createField("gmt_modified", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>yibot.t_city_overview.data</code>.
     */
    public final TableField<TCityOverviewRecord, String> DATA = createField("data", org.jooq.impl.SQLDataType.VARCHAR(4000).nullable(false), this, "");

    /**
     * Create a <code>yibot.t_city_overview</code> table reference
     */
    public TCityOverview() {
        this(DSL.name("t_city_overview"), null);
    }

    /**
     * Create an aliased <code>yibot.t_city_overview</code> table reference
     */
    public TCityOverview(String alias) {
        this(DSL.name(alias), T_CITY_OVERVIEW);
    }

    /**
     * Create an aliased <code>yibot.t_city_overview</code> table reference
     */
    public TCityOverview(Name alias) {
        this(alias, T_CITY_OVERVIEW);
    }

    private TCityOverview(Name alias, Table<TCityOverviewRecord> aliased) {
        this(alias, aliased, null);
    }

    private TCityOverview(Name alias, Table<TCityOverviewRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("各城市faq数据统计表"));
    }

    public <O extends Record> TCityOverview(Table<O> child, ForeignKey<O, TCityOverviewRecord> key) {
        super(child, key, T_CITY_OVERVIEW);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Yibot.YIBOT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.T_CITY_OVERVIEW_IDX_DS_IT, Indexes.T_CITY_OVERVIEW_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TCityOverviewRecord> getPrimaryKey() {
        return Keys.KEY_T_CITY_OVERVIEW_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TCityOverviewRecord>> getKeys() {
        return Arrays.<UniqueKey<TCityOverviewRecord>>asList(Keys.KEY_T_CITY_OVERVIEW_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TCityOverview as(String alias) {
        return new TCityOverview(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TCityOverview as(Name alias) {
        return new TCityOverview(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TCityOverview rename(String name) {
        return new TCityOverview(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TCityOverview rename(Name name) {
        return new TCityOverview(name, null);
    }
}
