/*
 * This file is generated by jOOQ.
 */
package com.zhuiyi.model.jooq.tables;


import com.zhuiyi.model.jooq.Indexes;
import com.zhuiyi.model.jooq.Keys;
import com.zhuiyi.model.jooq.Yibot;
import com.zhuiyi.model.jooq.tables.records.TDialogDetailRecord;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;


/**
 * 机器对话流水明细表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TDialogDetail extends TableImpl<TDialogDetailRecord> {

    private static final long serialVersionUID = 1172395839;

    /**
     * The reference instance of <code>yibot.t_dialog_detail</code>
     */
    public static final TDialogDetail T_DIALOG_DETAIL = new TDialogDetail();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TDialogDetailRecord> getRecordType() {
        return TDialogDetailRecord.class;
    }

    /**
     * The column <code>yibot.t_dialog_detail.id</code>.
     */
    public final TableField<TDialogDetailRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>yibot.t_dialog_detail.appid</code>.
     */
    public final TableField<TDialogDetailRecord, String> APPID = createField("appid", org.jooq.impl.SQLDataType.VARCHAR(30).nullable(false), this, "");

    /**
     * The column <code>yibot.t_dialog_detail.date_month</code>.
     */
    public final TableField<TDialogDetailRecord, String> DATE_MONTH = createField("date_month", org.jooq.impl.SQLDataType.CHAR(10).nullable(false), this, "");

    /**
     * The column <code>yibot.t_dialog_detail.exact_time</code>.
     */
    public final TableField<TDialogDetailRecord, Timestamp> EXACT_TIME = createField("exact_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>yibot.t_dialog_detail.recv_time</code>.
     */
    public final TableField<TDialogDetailRecord, Timestamp> RECV_TIME = createField("recv_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>yibot.t_dialog_detail.retmsg</code>.
     */
    public final TableField<TDialogDetailRecord, String> RETMSG = createField("retmsg", org.jooq.impl.SQLDataType.VARCHAR(250), this, "");

    /**
     * The column <code>yibot.t_dialog_detail.direct_faq_id</code>.
     */
    public final TableField<TDialogDetailRecord, String> DIRECT_FAQ_ID = createField("direct_faq_id", org.jooq.impl.SQLDataType.VARCHAR(10).nullable(false), this, "");

    /**
     * The column <code>yibot.t_dialog_detail.indirect_faq_id</code>.
     */
    public final TableField<TDialogDetailRecord, String> INDIRECT_FAQ_ID = createField("indirect_faq_id", org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>yibot.t_dialog_detail.direct_faq</code>.
     */
    public final TableField<TDialogDetailRecord, String> DIRECT_FAQ = createField("direct_faq", org.jooq.impl.SQLDataType.VARCHAR(400), this, "");

    /**
     * The column <code>yibot.t_dialog_detail.indirect_faq</code>.
     */
    public final TableField<TDialogDetailRecord, String> INDIRECT_FAQ = createField("indirect_faq", org.jooq.impl.SQLDataType.VARCHAR(4000), this, "");

    /**
     * The column <code>yibot.t_dialog_detail.user_ip</code>.
     */
    public final TableField<TDialogDetailRecord, String> USER_IP = createField("user_ip", org.jooq.impl.SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>yibot.t_dialog_detail.query</code>.
     */
    public final TableField<TDialogDetailRecord, String> QUERY = createField("query", org.jooq.impl.SQLDataType.VARCHAR(3000), this, "");

    /**
     * The column <code>yibot.t_dialog_detail.answer</code>.
     */
    public final TableField<TDialogDetailRecord, String> ANSWER = createField("answer", org.jooq.impl.SQLDataType.VARCHAR(5000), this, "");

    /**
     * The column <code>yibot.t_dialog_detail.biz_portal</code>.
     */
    public final TableField<TDialogDetailRecord, String> BIZ_PORTAL = createField("biz_portal", org.jooq.impl.SQLDataType.VARCHAR(30), this, "");

    /**
     * The column <code>yibot.t_dialog_detail.biz_ret_code</code>.
     */
    public final TableField<TDialogDetailRecord, Boolean> BIZ_RET_CODE = createField("biz_ret_code", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>yibot.t_dialog_detail.biz_docid</code>.
     */
    public final TableField<TDialogDetailRecord, String> BIZ_DOCID = createField("biz_docid", org.jooq.impl.SQLDataType.VARCHAR(800), this, "");

    /**
     * The column <code>yibot.t_dialog_detail.biz_ret_str</code>.
     */
    public final TableField<TDialogDetailRecord, String> BIZ_RET_STR = createField("biz_ret_str", org.jooq.impl.SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>yibot.t_dialog_detail.ccd_cost</code>.
     */
    public final TableField<TDialogDetailRecord, Integer> CCD_COST = createField("ccd_cost", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>yibot.t_dialog_detail.x_forward</code>.
     */
    public final TableField<TDialogDetailRecord, String> X_FORWARD = createField("x_forward", org.jooq.impl.SQLDataType.VARCHAR(10), this, "");

    /**
     * The column <code>yibot.t_dialog_detail.biz_cost</code>.
     */
    public final TableField<TDialogDetailRecord, Integer> BIZ_COST = createField("biz_cost", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>yibot.t_dialog_detail.answer_index</code>.
     */
    public final TableField<TDialogDetailRecord, String> ANSWER_INDEX = createField("answer_index", org.jooq.impl.SQLDataType.VARCHAR(10), this, "");

    /**
     * The column <code>yibot.t_dialog_detail.place</code>.
     */
    public final TableField<TDialogDetailRecord, String> PLACE = createField("place", org.jooq.impl.SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>yibot.t_dialog_detail.other</code>.
     */
    public final TableField<TDialogDetailRecord, String> OTHER = createField("other", org.jooq.impl.SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>yibot.t_dialog_detail.sen_level</code>.
     */
    public final TableField<TDialogDetailRecord, Boolean> SEN_LEVEL = createField("sen_level", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>yibot.t_dialog_detail.sen_words</code>.
     */
    public final TableField<TDialogDetailRecord, String> SEN_WORDS = createField("sen_words", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>yibot.t_dialog_detail.confidence</code>.
     */
    public final TableField<TDialogDetailRecord, String> CONFIDENCE = createField("confidence", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * Create a <code>yibot.t_dialog_detail</code> table reference
     */
    public TDialogDetail() {
        this(DSL.name("t_dialog_detail"), null);
    }

    /**
     * Create an aliased <code>yibot.t_dialog_detail</code> table reference
     */
    public TDialogDetail(String alias) {
        this(DSL.name(alias), T_DIALOG_DETAIL);
    }

    /**
     * Create an aliased <code>yibot.t_dialog_detail</code> table reference
     */
    public TDialogDetail(Name alias) {
        this(alias, T_DIALOG_DETAIL);
    }

    private TDialogDetail(Name alias, Table<TDialogDetailRecord> aliased) {
        this(alias, aliased, null);
    }

    private TDialogDetail(Name alias, Table<TDialogDetailRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("机器对话流水明细表"));
    }

    public <O extends Record> TDialogDetail(Table<O> child, ForeignKey<O, TDialogDetailRecord> key) {
        super(child, key, T_DIALOG_DETAIL);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Yibot.YIBOT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.T_DIALOG_DETAIL_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TDialogDetailRecord> getPrimaryKey() {
        return Keys.KEY_T_DIALOG_DETAIL_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TDialogDetailRecord>> getKeys() {
        return Arrays.<UniqueKey<TDialogDetailRecord>>asList(Keys.KEY_T_DIALOG_DETAIL_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDialogDetail as(String alias) {
        return new TDialogDetail(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDialogDetail as(Name alias) {
        return new TDialogDetail(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TDialogDetail rename(String name) {
        return new TDialogDetail(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TDialogDetail rename(Name name) {
        return new TDialogDetail(name, null);
    }
}
