/*
 * This file is generated by jOOQ.
 */
package com.zhuiyi.model.jooq.tables;


import com.zhuiyi.model.jooq.Indexes;
import com.zhuiyi.model.jooq.Keys;
import com.zhuiyi.model.jooq.Yibot;
import com.zhuiyi.model.jooq.tables.records.TDialogRecord;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;

import javax.annotation.Generated;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;


/**
 * 机器对话流水表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TDialog extends TableImpl<TDialogRecord> {

    private static final long serialVersionUID = -1376778761;

    /**
     * The reference instance of <code>yibot.t_dialog</code>
     */
    public static final TDialog T_DIALOG = new TDialog();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TDialogRecord> getRecordType() {
        return TDialogRecord.class;
    }

    /**
     * The column <code>yibot.t_dialog.id</code>.
     */
    public final TableField<TDialogRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>yibot.t_dialog.appid</code>.
     */
    public final TableField<TDialogRecord, String> APPID = createField("appid", org.jooq.impl.SQLDataType.VARCHAR(30).nullable(false), this, "");

    /**
     * The column <code>yibot.t_dialog.date_month</code>.
     */
    public final TableField<TDialogRecord, String> DATE_MONTH = createField("date_month", org.jooq.impl.SQLDataType.CHAR(10).nullable(false), this, "");

    /**
     * The column <code>yibot.t_dialog.exact_time</code>.
     */
    public final TableField<TDialogRecord, Timestamp> EXACT_TIME = createField("exact_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>yibot.t_dialog.date_sign</code>.
     */
    public final TableField<TDialogRecord, String> DATE_SIGN = createField("date_sign", org.jooq.impl.SQLDataType.CHAR(10).nullable(false), this, "");

    /**
     * The column <code>yibot.t_dialog.session_id</code>.
     */
    public final TableField<TDialogRecord, String> SESSION_ID = createField("session_id", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>yibot.t_dialog.search_id</code>.
     */
    public final TableField<TDialogRecord, String> SEARCH_ID = createField("search_id", org.jooq.impl.SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>yibot.t_dialog.answer_type</code>.
     */
    public final TableField<TDialogRecord, String> ANSWER_TYPE = createField("answer_type", org.jooq.impl.SQLDataType.VARCHAR(10), this, "");

    /**
     * The column <code>yibot.t_dialog.faq_num</code>.
     */
    public final TableField<TDialogRecord, Boolean> FAQ_NUM = createField("faq_num", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>yibot.t_dialog.retcode</code>.
     */
    public final TableField<TDialogRecord, Boolean> RETCODE = createField("retcode", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>yibot.t_dialog.ten_min</code>.
     */
    public final TableField<TDialogRecord, String> TEN_MIN = createField("ten_min", org.jooq.impl.SQLDataType.CHAR(10).nullable(false), this, "");

    /**
     * The column <code>yibot.t_dialog.source</code>.
     */
    public final TableField<TDialogRecord, String> SOURCE = createField("source", org.jooq.impl.SQLDataType.VARCHAR(30), this, "");

    /**
     * The column <code>yibot.t_dialog.account</code>.
     */
    public final TableField<TDialogRecord, String> ACCOUNT = createField("account", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>yibot.t_dialog.country</code>.
     */
    public final TableField<TDialogRecord, String> COUNTRY = createField("country", org.jooq.impl.SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>yibot.t_dialog.province</code>.
     */
    public final TableField<TDialogRecord, String> PROVINCE = createField("province", org.jooq.impl.SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>yibot.t_dialog.city</code>.
     */
    public final TableField<TDialogRecord, String> CITY = createField("city", org.jooq.impl.SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>yibot.t_dialog.is_reject</code>.
     */
    public final TableField<TDialogRecord, Boolean> IS_REJECT = createField("is_reject", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>yibot.t_dialog.is_click_good</code>.
     */
    public final TableField<TDialogRecord, Boolean> IS_CLICK_GOOD = createField("is_click_good", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>yibot.t_dialog.is_click_bad</code>.
     */
    public final TableField<TDialogRecord, Boolean> IS_CLICK_BAD = createField("is_click_bad", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>yibot.t_dialog.is_zrg</code>.
     */
    public final TableField<TDialogRecord, String> IS_ZRG = createField("is_zrg", org.jooq.impl.SQLDataType.CHAR(6), this, "");

    /**
     * The column <code>yibot.t_dialog.adaptor_cost</code>.
     */
    public final TableField<TDialogRecord, UInteger> ADAPTOR_COST = createField("adaptor_cost", org.jooq.impl.SQLDataType.INTEGERUNSIGNED, this, "");

    /**
     * The column <code>yibot.t_dialog.clientip</code>.
     */
    public final TableField<TDialogRecord, String> CLIENTIP = createField("clientip", org.jooq.impl.SQLDataType.VARCHAR(30), this, "");

    /**
     * The column <code>yibot.t_dialog.biz_type</code>.
     */
    public final TableField<TDialogRecord, Boolean> BIZ_TYPE = createField("biz_type", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>yibot.t_dialog.business_name</code>.
     */
    public final TableField<TDialogRecord, String> BUSINESS_NAME = createField("business_name", org.jooq.impl.SQLDataType.VARCHAR(30), this, "");

    /**
     * The column <code>yibot.t_dialog.is_assistant</code>.
     */
    public final TableField<TDialogRecord, Boolean> IS_ASSISTANT = createField("is_assistant", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>yibot.t_dialog.channel</code>.
     */
    public final TableField<TDialogRecord, String> CHANNEL = createField("channel", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>yibot.t_dialog.cid</code>.
     */
    public final TableField<TDialogRecord, String> CID = createField("cid", org.jooq.impl.SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>yibot.t_dialog.eid</code>.
     */
    public final TableField<TDialogRecord, String> EID = createField("eid", org.jooq.impl.SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>yibot.t_dialog.lables</code>.
     */
    public final TableField<TDialogRecord, String> LABLES = createField("lables", org.jooq.impl.SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>yibot.t_dialog.im</code>.
     */
    public final TableField<TDialogRecord, String> IM = createField("im", org.jooq.impl.SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>yibot.t_dialog.client</code>.
     */
    public final TableField<TDialogRecord, String> CLIENT = createField("client", org.jooq.impl.SQLDataType.VARCHAR(30), this, "");

    /**
     * The column <code>yibot.t_dialog.tags</code>.
     */
    public final TableField<TDialogRecord, String> TAGS = createField("tags", org.jooq.impl.SQLDataType.VARCHAR(30), this, "");

    /**
     * The column <code>yibot.t_dialog.gmt_create</code>.
     */
    public final TableField<TDialogRecord, Timestamp> GMT_CREATE = createField("gmt_create", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>yibot.t_dialog.gmt_modified</code>.
     */
    public final TableField<TDialogRecord, Timestamp> GMT_MODIFIED = createField("gmt_modified", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>yibot.t_dialog.reserved1</code>.
     */
    public final TableField<TDialogRecord, String> RESERVED1 = createField("reserved1", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>yibot.t_dialog.reserved2</code>.
     */
    public final TableField<TDialogRecord, String> RESERVED2 = createField("reserved2", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>yibot.t_dialog.reserved3</code>.
     */
    public final TableField<TDialogRecord, String> RESERVED3 = createField("reserved3", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>yibot.t_dialog.reserved4</code>.
     */
    public final TableField<TDialogRecord, String> RESERVED4 = createField("reserved4", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>yibot.t_dialog.reserved5</code>.
     */
    public final TableField<TDialogRecord, String> RESERVED5 = createField("reserved5", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * Create a <code>yibot.t_dialog</code> table reference
     */
    public TDialog() {
        this(DSL.name("t_dialog"), null);
    }

    /**
     * Create an aliased <code>yibot.t_dialog</code> table reference
     */
    public TDialog(String alias) {
        this(DSL.name(alias), T_DIALOG);
    }

    /**
     * Create an aliased <code>yibot.t_dialog</code> table reference
     */
    public TDialog(Name alias) {
        this(alias, T_DIALOG);
    }

    private TDialog(Name alias, Table<TDialogRecord> aliased) {
        this(alias, aliased, null);
    }

    private TDialog(Name alias, Table<TDialogRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("机器对话流水表"));
    }

    public <O extends Record> TDialog(Table<O> child, ForeignKey<O, TDialogRecord> key) {
        super(child, key, T_DIALOG);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Yibot.YIBOT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.T_DIALOG_IDX_DATE_SIGN, Indexes.T_DIALOG_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TDialogRecord> getPrimaryKey() {
        return Keys.KEY_T_DIALOG_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TDialogRecord>> getKeys() {
        return Arrays.<UniqueKey<TDialogRecord>>asList(Keys.KEY_T_DIALOG_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDialog as(String alias) {
        return new TDialog(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDialog as(Name alias) {
        return new TDialog(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TDialog rename(String name) {
        return new TDialog(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TDialog rename(Name name) {
        return new TDialog(name, null);
    }
}
