/*
 * This file is generated by jOOQ.
 */
package com.zhuiyi.model.jooq.tables;


import com.zhuiyi.model.jooq.Indexes;
import com.zhuiyi.model.jooq.Keys;
import com.zhuiyi.model.jooq.Yibot;
import com.zhuiyi.model.jooq.tables.records.TFaqTouchOverviewRecord;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;

import javax.annotation.Generated;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;


/**
 * faq触达数据统计表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TFaqTouchOverview extends TableImpl<TFaqTouchOverviewRecord> {

    private static final long serialVersionUID = -1865339372;

    /**
     * The reference instance of <code>yibot.t_faq_touch_overview</code>
     */
    public static final TFaqTouchOverview T_FAQ_TOUCH_OVERVIEW = new TFaqTouchOverview();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TFaqTouchOverviewRecord> getRecordType() {
        return TFaqTouchOverviewRecord.class;
    }

    /**
     * The column <code>yibot.t_faq_touch_overview.id</code>.
     */
    public final TableField<TFaqTouchOverviewRecord, ULong> ID = createField("id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>yibot.t_faq_touch_overview.appid</code>.
     */
    public final TableField<TFaqTouchOverviewRecord, String> APPID = createField("appid", org.jooq.impl.SQLDataType.VARCHAR(30).nullable(false), this, "");

    /**
     * The column <code>yibot.t_faq_touch_overview.date_sign</code>.
     */
    public final TableField<TFaqTouchOverviewRecord, String> DATE_SIGN = createField("date_sign", org.jooq.impl.SQLDataType.CHAR(10).nullable(false), this, "");

    /**
     * The column <code>yibot.t_faq_touch_overview.faq_id</code>.
     */
    public final TableField<TFaqTouchOverviewRecord, Integer> FAQ_ID = createField("faq_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>yibot.t_faq_touch_overview.faq</code>.
     */
    public final TableField<TFaqTouchOverviewRecord, String> FAQ = createField("faq", org.jooq.impl.SQLDataType.VARCHAR(500), this, "");

    /**
     * The column <code>yibot.t_faq_touch_overview.category_id</code>.
     */
    public final TableField<TFaqTouchOverviewRecord, String> CATEGORY_ID = createField("category_id", org.jooq.impl.SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>yibot.t_faq_touch_overview.touch_num</code>.
     */
    public final TableField<TFaqTouchOverviewRecord, Integer> TOUCH_NUM = createField("touch_num", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>yibot.t_faq_touch_overview.direct_num</code>.
     */
    public final TableField<TFaqTouchOverviewRecord, Integer> DIRECT_NUM = createField("direct_num", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>yibot.t_faq_touch_overview.recommend_num</code>.
     */
    public final TableField<TFaqTouchOverviewRecord, Integer> RECOMMEND_NUM = createField("recommend_num", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>yibot.t_faq_touch_overview.recommend_ans_num</code>.
     */
    public final TableField<TFaqTouchOverviewRecord, Integer> RECOMMEND_ANS_NUM = createField("recommend_ans_num", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>yibot.t_faq_touch_overview.click_good</code>.
     */
    public final TableField<TFaqTouchOverviewRecord, Integer> CLICK_GOOD = createField("click_good", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>yibot.t_faq_touch_overview.click_bad</code>.
     */
    public final TableField<TFaqTouchOverviewRecord, Integer> CLICK_BAD = createField("click_bad", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>yibot.t_faq_touch_overview.touch_rate</code>.
     */
    public final TableField<TFaqTouchOverviewRecord, String> TOUCH_RATE = createField("touch_rate", org.jooq.impl.SQLDataType.VARCHAR(30), this, "");

    /**
     * The column <code>yibot.t_faq_touch_overview.zd_zrg</code>.
     */
    public final TableField<TFaqTouchOverviewRecord, Integer> ZD_ZRG = createField("zd_zrg", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>yibot.t_faq_touch_overview.bd_zrg</code>.
     */
    public final TableField<TFaqTouchOverviewRecord, Integer> BD_ZRG = createField("bd_zrg", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>yibot.t_faq_touch_overview.total_zrg</code>.
     */
    public final TableField<TFaqTouchOverviewRecord, Integer> TOTAL_ZRG = createField("total_zrg", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>yibot.t_faq_touch_overview.click_good_rate</code>.
     */
    public final TableField<TFaqTouchOverviewRecord, String> CLICK_GOOD_RATE = createField("click_good_rate", org.jooq.impl.SQLDataType.VARCHAR(30), this, "");

    /**
     * The column <code>yibot.t_faq_touch_overview.click_bad_rate</code>.
     */
    public final TableField<TFaqTouchOverviewRecord, String> CLICK_BAD_RATE = createField("click_bad_rate", org.jooq.impl.SQLDataType.VARCHAR(30), this, "");

    /**
     * The column <code>yibot.t_faq_touch_overview.biz_type</code>.
     */
    public final TableField<TFaqTouchOverviewRecord, String> BIZ_TYPE = createField("biz_type", org.jooq.impl.SQLDataType.VARCHAR(10), this, "");

    /**
     * The column <code>yibot.t_faq_touch_overview.total_click</code>.
     */
    public final TableField<TFaqTouchOverviewRecord, Integer> TOTAL_CLICK = createField("total_click", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>yibot.t_faq_touch_overview.zrg_rate</code>.
     */
    public final TableField<TFaqTouchOverviewRecord, String> ZRG_RATE = createField("zrg_rate", org.jooq.impl.SQLDataType.VARCHAR(30), this, "");

    /**
     * The column <code>yibot.t_faq_touch_overview.labels</code>.
     */
    public final TableField<TFaqTouchOverviewRecord, String> LABELS = createField("labels", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>yibot.t_faq_touch_overview.gmt_create</code>.
     */
    public final TableField<TFaqTouchOverviewRecord, Timestamp> GMT_CREATE = createField("gmt_create", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>yibot.t_faq_touch_overview.gmt_modified</code>.
     */
    public final TableField<TFaqTouchOverviewRecord, Timestamp> GMT_MODIFIED = createField("gmt_modified", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * Create a <code>yibot.t_faq_touch_overview</code> table reference
     */
    public TFaqTouchOverview() {
        this(DSL.name("t_faq_touch_overview"), null);
    }

    /**
     * Create an aliased <code>yibot.t_faq_touch_overview</code> table reference
     */
    public TFaqTouchOverview(String alias) {
        this(DSL.name(alias), T_FAQ_TOUCH_OVERVIEW);
    }

    /**
     * Create an aliased <code>yibot.t_faq_touch_overview</code> table reference
     */
    public TFaqTouchOverview(Name alias) {
        this(alias, T_FAQ_TOUCH_OVERVIEW);
    }

    private TFaqTouchOverview(Name alias, Table<TFaqTouchOverviewRecord> aliased) {
        this(alias, aliased, null);
    }

    private TFaqTouchOverview(Name alias, Table<TFaqTouchOverviewRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("faq触达数据统计表"));
    }

    public <O extends Record> TFaqTouchOverview(Table<O> child, ForeignKey<O, TFaqTouchOverviewRecord> key) {
        super(child, key, T_FAQ_TOUCH_OVERVIEW);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Yibot.YIBOT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.T_FAQ_TOUCH_OVERVIEW_IDX_DS_FI, Indexes.T_FAQ_TOUCH_OVERVIEW_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TFaqTouchOverviewRecord> getPrimaryKey() {
        return Keys.KEY_T_FAQ_TOUCH_OVERVIEW_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TFaqTouchOverviewRecord>> getKeys() {
        return Arrays.<UniqueKey<TFaqTouchOverviewRecord>>asList(Keys.KEY_T_FAQ_TOUCH_OVERVIEW_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TFaqTouchOverview as(String alias) {
        return new TFaqTouchOverview(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TFaqTouchOverview as(Name alias) {
        return new TFaqTouchOverview(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TFaqTouchOverview rename(String name) {
        return new TFaqTouchOverview(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TFaqTouchOverview rename(Name name) {
        return new TFaqTouchOverview(name, null);
    }
}
