/*
 * This file is generated by jOOQ.
 */
package com.zhuiyi.model.jooq.tables;


import com.zhuiyi.model.jooq.Indexes;
import com.zhuiyi.model.jooq.Keys;
import com.zhuiyi.model.jooq.Yibot;
import com.zhuiyi.model.jooq.tables.records.TFeedbackBackRecord;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;

import javax.annotation.Generated;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;


/**
 * 原始feedback数据记录表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TFeedbackBack extends TableImpl<TFeedbackBackRecord> {

    private static final long serialVersionUID = -1451069390;

    /**
     * The reference instance of <code>yibot.t_feedback_back</code>
     */
    public static final TFeedbackBack T_FEEDBACK_BACK = new TFeedbackBack();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TFeedbackBackRecord> getRecordType() {
        return TFeedbackBackRecord.class;
    }

    /**
     * The column <code>yibot.t_feedback_back.id</code>.
     */
    public final TableField<TFeedbackBackRecord, ULong> ID = createField("id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>yibot.t_feedback_back.appid</code>.
     */
    public final TableField<TFeedbackBackRecord, String> APPID = createField("appid", org.jooq.impl.SQLDataType.VARCHAR(30).nullable(false), this, "");

    /**
     * The column <code>yibot.t_feedback_back.exact_time</code>.
     */
    public final TableField<TFeedbackBackRecord, Timestamp> EXACT_TIME = createField("exact_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>yibot.t_feedback_back.gmt_create</code>.
     */
    public final TableField<TFeedbackBackRecord, Timestamp> GMT_CREATE = createField("gmt_create", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>yibot.t_feedback_back.gmt_modified</code>.
     */
    public final TableField<TFeedbackBackRecord, Timestamp> GMT_MODIFIED = createField("gmt_modified", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>yibot.t_feedback_back.data</code>.
     */
    public final TableField<TFeedbackBackRecord, String> DATA = createField("data", org.jooq.impl.SQLDataType.VARCHAR(4000).nullable(false), this, "");

    /**
     * Create a <code>yibot.t_feedback_back</code> table reference
     */
    public TFeedbackBack() {
        this(DSL.name("t_feedback_back"), null);
    }

    /**
     * Create an aliased <code>yibot.t_feedback_back</code> table reference
     */
    public TFeedbackBack(String alias) {
        this(DSL.name(alias), T_FEEDBACK_BACK);
    }

    /**
     * Create an aliased <code>yibot.t_feedback_back</code> table reference
     */
    public TFeedbackBack(Name alias) {
        this(alias, T_FEEDBACK_BACK);
    }

    private TFeedbackBack(Name alias, Table<TFeedbackBackRecord> aliased) {
        this(alias, aliased, null);
    }

    private TFeedbackBack(Name alias, Table<TFeedbackBackRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("原始feedback数据记录表"));
    }

    public <O extends Record> TFeedbackBack(Table<O> child, ForeignKey<O, TFeedbackBackRecord> key) {
        super(child, key, T_FEEDBACK_BACK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Yibot.YIBOT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.T_FEEDBACK_BACK_IDX_EXACT_TIME, Indexes.T_FEEDBACK_BACK_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TFeedbackBackRecord> getPrimaryKey() {
        return Keys.KEY_T_FEEDBACK_BACK_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TFeedbackBackRecord>> getKeys() {
        return Arrays.<UniqueKey<TFeedbackBackRecord>>asList(Keys.KEY_T_FEEDBACK_BACK_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TFeedbackBack as(String alias) {
        return new TFeedbackBack(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TFeedbackBack as(Name alias) {
        return new TFeedbackBack(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TFeedbackBack rename(String name) {
        return new TFeedbackBack(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TFeedbackBack rename(Name name) {
        return new TFeedbackBack(name, null);
    }
}
