/*
 * This file is generated by jOOQ.
 */
package com.zhuiyi.model.jooq.tables;


import com.zhuiyi.model.jooq.Indexes;
import com.zhuiyi.model.jooq.Keys;
import com.zhuiyi.model.jooq.Yibot;
import com.zhuiyi.model.jooq.tables.records.THotAreaFqOverviewRecord;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;

import javax.annotation.Generated;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;


/**
 * 热点区域FAQ数据统计表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class THotAreaFqOverview extends TableImpl<THotAreaFqOverviewRecord> {

    private static final long serialVersionUID = -1729072973;

    /**
     * The reference instance of <code>yibot.t_hot_area_fq_overview</code>
     */
    public static final THotAreaFqOverview T_HOT_AREA_FQ_OVERVIEW = new THotAreaFqOverview();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<THotAreaFqOverviewRecord> getRecordType() {
        return THotAreaFqOverviewRecord.class;
    }

    /**
     * The column <code>yibot.t_hot_area_fq_overview.id</code>.
     */
    public final TableField<THotAreaFqOverviewRecord, ULong> ID = createField("id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>yibot.t_hot_area_fq_overview.appid</code>.
     */
    public final TableField<THotAreaFqOverviewRecord, String> APPID = createField("appid", org.jooq.impl.SQLDataType.VARCHAR(30).nullable(false), this, "");

    /**
     * The column <code>yibot.t_hot_area_fq_overview.date_sign</code>.
     */
    public final TableField<THotAreaFqOverviewRecord, String> DATE_SIGN = createField("date_sign", org.jooq.impl.SQLDataType.CHAR(10).nullable(false), this, "");

    /**
     * The column <code>yibot.t_hot_area_fq_overview.area_type</code>.
     */
    public final TableField<THotAreaFqOverviewRecord, Boolean> AREA_TYPE = createField("area_type", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>yibot.t_hot_area_fq_overview.area_name</code>.
     */
    public final TableField<THotAreaFqOverviewRecord, String> AREA_NAME = createField("area_name", org.jooq.impl.SQLDataType.CHAR(10), this, "");

    /**
     * The column <code>yibot.t_hot_area_fq_overview.faq_id</code>.
     */
    public final TableField<THotAreaFqOverviewRecord, Integer> FAQ_ID = createField("faq_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>yibot.t_hot_area_fq_overview.faq</code>.
     */
    public final TableField<THotAreaFqOverviewRecord, String> FAQ = createField("faq", org.jooq.impl.SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>yibot.t_hot_area_fq_overview.visit_num</code>.
     */
    public final TableField<THotAreaFqOverviewRecord, Integer> VISIT_NUM = createField("visit_num", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>yibot.t_hot_area_fq_overview.visit_trend</code>.
     */
    public final TableField<THotAreaFqOverviewRecord, String> VISIT_TREND = createField("visit_trend", org.jooq.impl.SQLDataType.CHAR(20).nullable(false), this, "");

    /**
     * The column <code>yibot.t_hot_area_fq_overview.gmt_create</code>.
     */
    public final TableField<THotAreaFqOverviewRecord, Timestamp> GMT_CREATE = createField("gmt_create", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>yibot.t_hot_area_fq_overview.gmt_modified</code>.
     */
    public final TableField<THotAreaFqOverviewRecord, Timestamp> GMT_MODIFIED = createField("gmt_modified", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * Create a <code>yibot.t_hot_area_fq_overview</code> table reference
     */
    public THotAreaFqOverview() {
        this(DSL.name("t_hot_area_fq_overview"), null);
    }

    /**
     * Create an aliased <code>yibot.t_hot_area_fq_overview</code> table reference
     */
    public THotAreaFqOverview(String alias) {
        this(DSL.name(alias), T_HOT_AREA_FQ_OVERVIEW);
    }

    /**
     * Create an aliased <code>yibot.t_hot_area_fq_overview</code> table reference
     */
    public THotAreaFqOverview(Name alias) {
        this(alias, T_HOT_AREA_FQ_OVERVIEW);
    }

    private THotAreaFqOverview(Name alias, Table<THotAreaFqOverviewRecord> aliased) {
        this(alias, aliased, null);
    }

    private THotAreaFqOverview(Name alias, Table<THotAreaFqOverviewRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("热点区域FAQ数据统计表"));
    }

    public <O extends Record> THotAreaFqOverview(Table<O> child, ForeignKey<O, THotAreaFqOverviewRecord> key) {
        super(child, key, T_HOT_AREA_FQ_OVERVIEW);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Yibot.YIBOT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.T_HOT_AREA_FQ_OVERVIEW_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<THotAreaFqOverviewRecord> getPrimaryKey() {
        return Keys.KEY_T_HOT_AREA_FQ_OVERVIEW_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<THotAreaFqOverviewRecord>> getKeys() {
        return Arrays.<UniqueKey<THotAreaFqOverviewRecord>>asList(Keys.KEY_T_HOT_AREA_FQ_OVERVIEW_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public THotAreaFqOverview as(String alias) {
        return new THotAreaFqOverview(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public THotAreaFqOverview as(Name alias) {
        return new THotAreaFqOverview(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public THotAreaFqOverview rename(String name) {
        return new THotAreaFqOverview(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public THotAreaFqOverview rename(Name name) {
        return new THotAreaFqOverview(name, null);
    }
}
