/*
 * This file is generated by jOOQ.
 */
package com.zhuiyi.model.jooq.tables;


import com.zhuiyi.model.jooq.Indexes;
import com.zhuiyi.model.jooq.Keys;
import com.zhuiyi.model.jooq.Yibot;
import com.zhuiyi.model.jooq.tables.records.THotAreaOverviewRecord;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;

import javax.annotation.Generated;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;


/**
 * 热点区域数据统计表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class THotAreaOverview extends TableImpl<THotAreaOverviewRecord> {

    private static final long serialVersionUID = 1794445296;

    /**
     * The reference instance of <code>yibot.t_hot_area_overview</code>
     */
    public static final THotAreaOverview T_HOT_AREA_OVERVIEW = new THotAreaOverview();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<THotAreaOverviewRecord> getRecordType() {
        return THotAreaOverviewRecord.class;
    }

    /**
     * The column <code>yibot.t_hot_area_overview.id</code>.
     */
    public final TableField<THotAreaOverviewRecord, ULong> ID = createField("id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>yibot.t_hot_area_overview.appid</code>.
     */
    public final TableField<THotAreaOverviewRecord, String> APPID = createField("appid", org.jooq.impl.SQLDataType.VARCHAR(30).nullable(false), this, "");

    /**
     * The column <code>yibot.t_hot_area_overview.date_sign</code>.
     */
    public final TableField<THotAreaOverviewRecord, String> DATE_SIGN = createField("date_sign", org.jooq.impl.SQLDataType.CHAR(10).nullable(false), this, "");

    /**
     * The column <code>yibot.t_hot_area_overview.area_type</code>.
     */
    public final TableField<THotAreaOverviewRecord, Boolean> AREA_TYPE = createField("area_type", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>yibot.t_hot_area_overview.area_name</code>.
     */
    public final TableField<THotAreaOverviewRecord, String> AREA_NAME = createField("area_name", org.jooq.impl.SQLDataType.CHAR(10), this, "");

    /**
     * The column <code>yibot.t_hot_area_overview.visit_num</code>.
     */
    public final TableField<THotAreaOverviewRecord, Integer> VISIT_NUM = createField("visit_num", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>yibot.t_hot_area_overview.visit_trend</code>.
     */
    public final TableField<THotAreaOverviewRecord, String> VISIT_TREND = createField("visit_trend", org.jooq.impl.SQLDataType.CHAR(20).nullable(false), this, "");

    /**
     * The column <code>yibot.t_hot_area_overview.gmt_create</code>.
     */
    public final TableField<THotAreaOverviewRecord, Timestamp> GMT_CREATE = createField("gmt_create", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>yibot.t_hot_area_overview.gmt_modified</code>.
     */
    public final TableField<THotAreaOverviewRecord, Timestamp> GMT_MODIFIED = createField("gmt_modified", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * Create a <code>yibot.t_hot_area_overview</code> table reference
     */
    public THotAreaOverview() {
        this(DSL.name("t_hot_area_overview"), null);
    }

    /**
     * Create an aliased <code>yibot.t_hot_area_overview</code> table reference
     */
    public THotAreaOverview(String alias) {
        this(DSL.name(alias), T_HOT_AREA_OVERVIEW);
    }

    /**
     * Create an aliased <code>yibot.t_hot_area_overview</code> table reference
     */
    public THotAreaOverview(Name alias) {
        this(alias, T_HOT_AREA_OVERVIEW);
    }

    private THotAreaOverview(Name alias, Table<THotAreaOverviewRecord> aliased) {
        this(alias, aliased, null);
    }

    private THotAreaOverview(Name alias, Table<THotAreaOverviewRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("热点区域数据统计表"));
    }

    public <O extends Record> THotAreaOverview(Table<O> child, ForeignKey<O, THotAreaOverviewRecord> key) {
        super(child, key, T_HOT_AREA_OVERVIEW);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Yibot.YIBOT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.T_HOT_AREA_OVERVIEW_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<THotAreaOverviewRecord> getPrimaryKey() {
        return Keys.KEY_T_HOT_AREA_OVERVIEW_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<THotAreaOverviewRecord>> getKeys() {
        return Arrays.<UniqueKey<THotAreaOverviewRecord>>asList(Keys.KEY_T_HOT_AREA_OVERVIEW_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public THotAreaOverview as(String alias) {
        return new THotAreaOverview(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public THotAreaOverview as(Name alias) {
        return new THotAreaOverview(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public THotAreaOverview rename(String name) {
        return new THotAreaOverview(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public THotAreaOverview rename(Name name) {
        return new THotAreaOverview(name, null);
    }
}
