/*
 * This file is generated by jOOQ.
 */
package com.zhuiyi.model.jooq.tables;


import com.zhuiyi.model.jooq.Indexes;
import com.zhuiyi.model.jooq.Keys;
import com.zhuiyi.model.jooq.Yibot;
import com.zhuiyi.model.jooq.tables.records.TJudgeOverviewRecord;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;

import javax.annotation.Generated;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;


/**
 * 用户评价统计表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TJudgeOverview extends TableImpl<TJudgeOverviewRecord> {

    private static final long serialVersionUID = -562735681;

    /**
     * The reference instance of <code>yibot.t_judge_overview</code>
     */
    public static final TJudgeOverview T_JUDGE_OVERVIEW = new TJudgeOverview();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TJudgeOverviewRecord> getRecordType() {
        return TJudgeOverviewRecord.class;
    }

    /**
     * The column <code>yibot.t_judge_overview.id</code>.
     */
    public final TableField<TJudgeOverviewRecord, ULong> ID = createField("id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>yibot.t_judge_overview.appid</code>.
     */
    public final TableField<TJudgeOverviewRecord, String> APPID = createField("appid", org.jooq.impl.SQLDataType.VARCHAR(30).nullable(false), this, "");

    /**
     * The column <code>yibot.t_judge_overview.date_sign</code>.
     */
    public final TableField<TJudgeOverviewRecord, String> DATE_SIGN = createField("date_sign", org.jooq.impl.SQLDataType.CHAR(10).nullable(false), this, "");

    /**
     * The column <code>yibot.t_judge_overview.is_total</code>.
     */
    public final TableField<TJudgeOverviewRecord, Boolean> IS_TOTAL = createField("is_total", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>yibot.t_judge_overview.cid</code>.
     */
    public final TableField<TJudgeOverviewRecord, String> CID = createField("cid", org.jooq.impl.SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>yibot.t_judge_overview.client</code>.
     */
    public final TableField<TJudgeOverviewRecord, String> CLIENT = createField("client", org.jooq.impl.SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>yibot.t_judge_overview.eid</code>.
     */
    public final TableField<TJudgeOverviewRecord, String> EID = createField("eid", org.jooq.impl.SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>yibot.t_judge_overview.lables</code>.
     */
    public final TableField<TJudgeOverviewRecord, String> LABLES = createField("lables", org.jooq.impl.SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>yibot.t_judge_overview.im</code>.
     */
    public final TableField<TJudgeOverviewRecord, String> IM = createField("im", org.jooq.impl.SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>yibot.t_judge_overview.gmt_create</code>.
     */
    public final TableField<TJudgeOverviewRecord, Timestamp> GMT_CREATE = createField("gmt_create", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>yibot.t_judge_overview.gmt_modified</code>.
     */
    public final TableField<TJudgeOverviewRecord, Timestamp> GMT_MODIFIED = createField("gmt_modified", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>yibot.t_judge_overview.data</code>.
     */
    public final TableField<TJudgeOverviewRecord, String> DATA = createField("data", org.jooq.impl.SQLDataType.VARCHAR(4000).nullable(false), this, "");

    /**
     * Create a <code>yibot.t_judge_overview</code> table reference
     */
    public TJudgeOverview() {
        this(DSL.name("t_judge_overview"), null);
    }

    /**
     * Create an aliased <code>yibot.t_judge_overview</code> table reference
     */
    public TJudgeOverview(String alias) {
        this(DSL.name(alias), T_JUDGE_OVERVIEW);
    }

    /**
     * Create an aliased <code>yibot.t_judge_overview</code> table reference
     */
    public TJudgeOverview(Name alias) {
        this(alias, T_JUDGE_OVERVIEW);
    }

    private TJudgeOverview(Name alias, Table<TJudgeOverviewRecord> aliased) {
        this(alias, aliased, null);
    }

    private TJudgeOverview(Name alias, Table<TJudgeOverviewRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("用户评价统计表"));
    }

    public <O extends Record> TJudgeOverview(Table<O> child, ForeignKey<O, TJudgeOverviewRecord> key) {
        super(child, key, T_JUDGE_OVERVIEW);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Yibot.YIBOT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.T_JUDGE_OVERVIEW_IDX_DS_IT, Indexes.T_JUDGE_OVERVIEW_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TJudgeOverviewRecord> getPrimaryKey() {
        return Keys.KEY_T_JUDGE_OVERVIEW_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TJudgeOverviewRecord>> getKeys() {
        return Arrays.<UniqueKey<TJudgeOverviewRecord>>asList(Keys.KEY_T_JUDGE_OVERVIEW_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TJudgeOverview as(String alias) {
        return new TJudgeOverview(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TJudgeOverview as(Name alias) {
        return new TJudgeOverview(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TJudgeOverview rename(String name) {
        return new TJudgeOverview(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TJudgeOverview rename(Name name) {
        return new TJudgeOverview(name, null);
    }
}
