/*
 * This file is generated by jOOQ.
 */
package com.zhuiyi.model.jooq.tables;


import com.zhuiyi.model.jooq.Indexes;
import com.zhuiyi.model.jooq.Keys;
import com.zhuiyi.model.jooq.Yibot;
import com.zhuiyi.model.jooq.tables.records.TPartTrendOverviewRecord;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;

import javax.annotation.Generated;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;


/**
 * 耗时和访问量趋势统计表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TPartTrendOverview extends TableImpl<TPartTrendOverviewRecord> {

    private static final long serialVersionUID = -156545016;

    /**
     * The reference instance of <code>yibot.t_part_trend_overview</code>
     */
    public static final TPartTrendOverview T_PART_TREND_OVERVIEW = new TPartTrendOverview();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TPartTrendOverviewRecord> getRecordType() {
        return TPartTrendOverviewRecord.class;
    }

    /**
     * The column <code>yibot.t_part_trend_overview.id</code>.
     */
    public final TableField<TPartTrendOverviewRecord, ULong> ID = createField("id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>yibot.t_part_trend_overview.appid</code>.
     */
    public final TableField<TPartTrendOverviewRecord, String> APPID = createField("appid", org.jooq.impl.SQLDataType.VARCHAR(30).nullable(false), this, "");

    /**
     * The column <code>yibot.t_part_trend_overview.date_sign</code>.
     */
    public final TableField<TPartTrendOverviewRecord, String> DATE_SIGN = createField("date_sign", org.jooq.impl.SQLDataType.CHAR(10).nullable(false), this, "");

    /**
     * The column <code>yibot.t_part_trend_overview.is_total</code>.
     */
    public final TableField<TPartTrendOverviewRecord, Boolean> IS_TOTAL = createField("is_total", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>yibot.t_part_trend_overview.cid</code>.
     */
    public final TableField<TPartTrendOverviewRecord, String> CID = createField("cid", org.jooq.impl.SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>yibot.t_part_trend_overview.client</code>.
     */
    public final TableField<TPartTrendOverviewRecord, String> CLIENT = createField("client", org.jooq.impl.SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>yibot.t_part_trend_overview.eid</code>.
     */
    public final TableField<TPartTrendOverviewRecord, String> EID = createField("eid", org.jooq.impl.SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>yibot.t_part_trend_overview.lables</code>.
     */
    public final TableField<TPartTrendOverviewRecord, String> LABLES = createField("lables", org.jooq.impl.SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>yibot.t_part_trend_overview.im</code>.
     */
    public final TableField<TPartTrendOverviewRecord, String> IM = createField("im", org.jooq.impl.SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>yibot.t_part_trend_overview.gmt_create</code>.
     */
    public final TableField<TPartTrendOverviewRecord, Timestamp> GMT_CREATE = createField("gmt_create", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>yibot.t_part_trend_overview.gmt_modified</code>.
     */
    public final TableField<TPartTrendOverviewRecord, Timestamp> GMT_MODIFIED = createField("gmt_modified", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>yibot.t_part_trend_overview.data</code>.
     */
    public final TableField<TPartTrendOverviewRecord, String> DATA = createField("data", org.jooq.impl.SQLDataType.VARCHAR(4000).nullable(false), this, "");

    /**
     * Create a <code>yibot.t_part_trend_overview</code> table reference
     */
    public TPartTrendOverview() {
        this(DSL.name("t_part_trend_overview"), null);
    }

    /**
     * Create an aliased <code>yibot.t_part_trend_overview</code> table reference
     */
    public TPartTrendOverview(String alias) {
        this(DSL.name(alias), T_PART_TREND_OVERVIEW);
    }

    /**
     * Create an aliased <code>yibot.t_part_trend_overview</code> table reference
     */
    public TPartTrendOverview(Name alias) {
        this(alias, T_PART_TREND_OVERVIEW);
    }

    private TPartTrendOverview(Name alias, Table<TPartTrendOverviewRecord> aliased) {
        this(alias, aliased, null);
    }

    private TPartTrendOverview(Name alias, Table<TPartTrendOverviewRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("耗时和访问量趋势统计表"));
    }

    public <O extends Record> TPartTrendOverview(Table<O> child, ForeignKey<O, TPartTrendOverviewRecord> key) {
        super(child, key, T_PART_TREND_OVERVIEW);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Yibot.YIBOT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.T_PART_TREND_OVERVIEW_IDX_DS_IT, Indexes.T_PART_TREND_OVERVIEW_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TPartTrendOverviewRecord> getPrimaryKey() {
        return Keys.KEY_T_PART_TREND_OVERVIEW_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TPartTrendOverviewRecord>> getKeys() {
        return Arrays.<UniqueKey<TPartTrendOverviewRecord>>asList(Keys.KEY_T_PART_TREND_OVERVIEW_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPartTrendOverview as(String alias) {
        return new TPartTrendOverview(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPartTrendOverview as(Name alias) {
        return new TPartTrendOverview(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TPartTrendOverview rename(String name) {
        return new TPartTrendOverview(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TPartTrendOverview rename(Name name) {
        return new TPartTrendOverview(name, null);
    }
}
