/*
 * This file is generated by jOOQ.
 */
package com.zhuiyi.model.jooq.tables;


import com.zhuiyi.model.jooq.Indexes;
import com.zhuiyi.model.jooq.Keys;
import com.zhuiyi.model.jooq.Yibot;
import com.zhuiyi.model.jooq.tables.records.TSessionRecord;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;

import javax.annotation.Generated;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;


/**
 * 会话表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TSession extends TableImpl<TSessionRecord> {

    private static final long serialVersionUID = 360191131;

    /**
     * The reference instance of <code>yibot.t_session</code>
     */
    public static final TSession T_SESSION = new TSession();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TSessionRecord> getRecordType() {
        return TSessionRecord.class;
    }

    /**
     * The column <code>yibot.t_session.id</code>.
     */
    public final TableField<TSessionRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>yibot.t_session.appid</code>.
     */
    public final TableField<TSessionRecord, String> APPID = createField("appid", org.jooq.impl.SQLDataType.VARCHAR(30).nullable(false), this, "");

    /**
     * The column <code>yibot.t_session.date_month</code>.
     */
    public final TableField<TSessionRecord, String> DATE_MONTH = createField("date_month", org.jooq.impl.SQLDataType.CHAR(10).nullable(false), this, "");

    /**
     * The column <code>yibot.t_session.start_time</code>.
     */
    public final TableField<TSessionRecord, Timestamp> START_TIME = createField("start_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>yibot.t_session.end_time</code>.
     */
    public final TableField<TSessionRecord, Timestamp> END_TIME = createField("end_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>yibot.t_session.date_sign</code>.
     */
    public final TableField<TSessionRecord, String> DATE_SIGN = createField("date_sign", org.jooq.impl.SQLDataType.CHAR(10).nullable(false), this, "");

    /**
     * The column <code>yibot.t_session.round_num</code>.
     */
    public final TableField<TSessionRecord, Boolean> ROUND_NUM = createField("round_num", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>yibot.t_session.account</code>.
     */
    public final TableField<TSessionRecord, String> ACCOUNT = createField("account", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>yibot.t_session.user_ip</code>.
     */
    public final TableField<TSessionRecord, String> USER_IP = createField("user_ip", org.jooq.impl.SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>yibot.t_session.country</code>.
     */
    public final TableField<TSessionRecord, String> COUNTRY = createField("country", org.jooq.impl.SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>yibot.t_session.province</code>.
     */
    public final TableField<TSessionRecord, String> PROVINCE = createField("province", org.jooq.impl.SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>yibot.t_session.city</code>.
     */
    public final TableField<TSessionRecord, String> CITY = createField("city", org.jooq.impl.SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>yibot.t_session.sen_level</code>.
     */
    public final TableField<TSessionRecord, Boolean> SEN_LEVEL = createField("sen_level", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>yibot.t_session.judge_type</code>.
     */
    public final TableField<TSessionRecord, Boolean> JUDGE_TYPE = createField("judge_type", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>yibot.t_session.click_good_num</code>.
     */
    public final TableField<TSessionRecord, UInteger> CLICK_GOOD_NUM = createField("click_good_num", org.jooq.impl.SQLDataType.INTEGERUNSIGNED, this, "");

    /**
     * The column <code>yibot.t_session.click_bad_num</code>.
     */
    public final TableField<TSessionRecord, UInteger> CLICK_BAD_NUM = createField("click_bad_num", org.jooq.impl.SQLDataType.INTEGERUNSIGNED, this, "");

    /**
     * The column <code>yibot.t_session.source</code>.
     */
    public final TableField<TSessionRecord, String> SOURCE = createField("source", org.jooq.impl.SQLDataType.VARCHAR(30), this, "");

    /**
     * The column <code>yibot.t_session.zrg_type</code>.
     */
    public final TableField<TSessionRecord, String> ZRG_TYPE = createField("zrg_type", org.jooq.impl.SQLDataType.CHAR(6), this, "");

    /**
     * The column <code>yibot.t_session.zrg_at</code>.
     */
    public final TableField<TSessionRecord, Boolean> ZRG_AT = createField("zrg_at", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>yibot.t_session.business_name</code>.
     */
    public final TableField<TSessionRecord, String> BUSINESS_NAME = createField("business_name", org.jooq.impl.SQLDataType.VARCHAR(30), this, "");

    /**
     * The column <code>yibot.t_session.check_tag</code>.
     */
    public final TableField<TSessionRecord, String> CHECK_TAG = createField("check_tag", org.jooq.impl.SQLDataType.VARCHAR(10), this, "");

    /**
     * The column <code>yibot.t_session.has_hanxuan</code>.
     */
    public final TableField<TSessionRecord, Boolean> HAS_HANXUAN = createField("has_hanxuan", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>yibot.t_session.has_reject</code>.
     */
    public final TableField<TSessionRecord, Boolean> HAS_REJECT = createField("has_reject", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>yibot.t_session.has_ans1</code>.
     */
    public final TableField<TSessionRecord, Boolean> HAS_ANS1 = createField("has_ans1", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>yibot.t_session.has_ans3</code>.
     */
    public final TableField<TSessionRecord, Boolean> HAS_ANS3 = createField("has_ans3", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>yibot.t_session.has_assistant</code>.
     */
    public final TableField<TSessionRecord, Boolean> HAS_ASSISTANT = createField("has_assistant", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>yibot.t_session.has_adopted</code>.
     */
    public final TableField<TSessionRecord, Boolean> HAS_ADOPTED = createField("has_adopted", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>yibot.t_session.has_secondedit</code>.
     */
    public final TableField<TSessionRecord, Boolean> HAS_SECONDEDIT = createField("has_secondedit", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>yibot.t_session.has_abandoned</code>.
     */
    public final TableField<TSessionRecord, Boolean> HAS_ABANDONED = createField("has_abandoned", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>yibot.t_session.channel</code>.
     */
    public final TableField<TSessionRecord, String> CHANNEL = createField("channel", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>yibot.t_session.cid</code>.
     */
    public final TableField<TSessionRecord, String> CID = createField("cid", org.jooq.impl.SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>yibot.t_session.eid</code>.
     */
    public final TableField<TSessionRecord, String> EID = createField("eid", org.jooq.impl.SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>yibot.t_session.lables</code>.
     */
    public final TableField<TSessionRecord, String> LABLES = createField("lables", org.jooq.impl.SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>yibot.t_session.im</code>.
     */
    public final TableField<TSessionRecord, String> IM = createField("im", org.jooq.impl.SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>yibot.t_session.client</code>.
     */
    public final TableField<TSessionRecord, String> CLIENT = createField("client", org.jooq.impl.SQLDataType.VARCHAR(30), this, "");

    /**
     * The column <code>yibot.t_session.gmt_create</code>.
     */
    public final TableField<TSessionRecord, Timestamp> GMT_CREATE = createField("gmt_create", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>yibot.t_session.gmt_modified</code>.
     */
    public final TableField<TSessionRecord, Timestamp> GMT_MODIFIED = createField("gmt_modified", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>yibot.t_session.reserved1</code>.
     */
    public final TableField<TSessionRecord, String> RESERVED1 = createField("reserved1", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>yibot.t_session.reserved2</code>.
     */
    public final TableField<TSessionRecord, String> RESERVED2 = createField("reserved2", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>yibot.t_session.reserved3</code>.
     */
    public final TableField<TSessionRecord, String> RESERVED3 = createField("reserved3", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>yibot.t_session.reserved4</code>.
     */
    public final TableField<TSessionRecord, String> RESERVED4 = createField("reserved4", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>yibot.t_session.reserved5</code>.
     */
    public final TableField<TSessionRecord, String> RESERVED5 = createField("reserved5", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * Create a <code>yibot.t_session</code> table reference
     */
    public TSession() {
        this(DSL.name("t_session"), null);
    }

    /**
     * Create an aliased <code>yibot.t_session</code> table reference
     */
    public TSession(String alias) {
        this(DSL.name(alias), T_SESSION);
    }

    /**
     * Create an aliased <code>yibot.t_session</code> table reference
     */
    public TSession(Name alias) {
        this(alias, T_SESSION);
    }

    private TSession(Name alias, Table<TSessionRecord> aliased) {
        this(alias, aliased, null);
    }

    private TSession(Name alias, Table<TSessionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("会话表"));
    }

    public <O extends Record> TSession(Table<O> child, ForeignKey<O, TSessionRecord> key) {
        super(child, key, T_SESSION);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Yibot.YIBOT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.T_SESSION_IDX_ACCOUNT, Indexes.T_SESSION_IDX_DATE_SIGN, Indexes.T_SESSION_IDX_ST_SO_RN, Indexes.T_SESSION_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TSessionRecord> getPrimaryKey() {
        return Keys.KEY_T_SESSION_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TSessionRecord>> getKeys() {
        return Arrays.<UniqueKey<TSessionRecord>>asList(Keys.KEY_T_SESSION_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TSession as(String alias) {
        return new TSession(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TSession as(Name alias) {
        return new TSession(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TSession rename(String name) {
        return new TSession(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TSession rename(Name name) {
        return new TSession(name, null);
    }
}
