/*
 * This file is generated by jOOQ.
 */
package com.zhuiyi.model.jooq.tables;


import com.zhuiyi.model.jooq.Indexes;
import com.zhuiyi.model.jooq.Keys;
import com.zhuiyi.model.jooq.Yibot;
import com.zhuiyi.model.jooq.tables.records.TTouchOverviewRecord;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;

import javax.annotation.Generated;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;


/**
 * FAQ触达率数据统计表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TTouchOverview extends TableImpl<TTouchOverviewRecord> {

    private static final long serialVersionUID = 34081551;

    /**
     * The reference instance of <code>yibot.t_touch_overview</code>
     */
    public static final TTouchOverview T_TOUCH_OVERVIEW = new TTouchOverview();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TTouchOverviewRecord> getRecordType() {
        return TTouchOverviewRecord.class;
    }

    /**
     * The column <code>yibot.t_touch_overview.id</code>.
     */
    public final TableField<TTouchOverviewRecord, ULong> ID = createField("id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>yibot.t_touch_overview.appid</code>.
     */
    public final TableField<TTouchOverviewRecord, String> APPID = createField("appid", org.jooq.impl.SQLDataType.VARCHAR(30).nullable(false), this, "");

    /**
     * The column <code>yibot.t_touch_overview.date_sign</code>.
     */
    public final TableField<TTouchOverviewRecord, String> DATE_SIGN = createField("date_sign", org.jooq.impl.SQLDataType.CHAR(10).nullable(false), this, "");

    /**
     * The column <code>yibot.t_touch_overview.is_total</code>.
     */
    public final TableField<TTouchOverviewRecord, Boolean> IS_TOTAL = createField("is_total", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>yibot.t_touch_overview.cid</code>.
     */
    public final TableField<TTouchOverviewRecord, String> CID = createField("cid", org.jooq.impl.SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>yibot.t_touch_overview.client</code>.
     */
    public final TableField<TTouchOverviewRecord, String> CLIENT = createField("client", org.jooq.impl.SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>yibot.t_touch_overview.eid</code>.
     */
    public final TableField<TTouchOverviewRecord, String> EID = createField("eid", org.jooq.impl.SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>yibot.t_touch_overview.lables</code>.
     */
    public final TableField<TTouchOverviewRecord, String> LABLES = createField("lables", org.jooq.impl.SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>yibot.t_touch_overview.im</code>.
     */
    public final TableField<TTouchOverviewRecord, String> IM = createField("im", org.jooq.impl.SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>yibot.t_touch_overview.gmt_create</code>.
     */
    public final TableField<TTouchOverviewRecord, Timestamp> GMT_CREATE = createField("gmt_create", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>yibot.t_touch_overview.gmt_modified</code>.
     */
    public final TableField<TTouchOverviewRecord, Timestamp> GMT_MODIFIED = createField("gmt_modified", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>yibot.t_touch_overview.data</code>.
     */
    public final TableField<TTouchOverviewRecord, String> DATA = createField("data", org.jooq.impl.SQLDataType.VARCHAR(4000).nullable(false), this, "");

    /**
     * Create a <code>yibot.t_touch_overview</code> table reference
     */
    public TTouchOverview() {
        this(DSL.name("t_touch_overview"), null);
    }

    /**
     * Create an aliased <code>yibot.t_touch_overview</code> table reference
     */
    public TTouchOverview(String alias) {
        this(DSL.name(alias), T_TOUCH_OVERVIEW);
    }

    /**
     * Create an aliased <code>yibot.t_touch_overview</code> table reference
     */
    public TTouchOverview(Name alias) {
        this(alias, T_TOUCH_OVERVIEW);
    }

    private TTouchOverview(Name alias, Table<TTouchOverviewRecord> aliased) {
        this(alias, aliased, null);
    }

    private TTouchOverview(Name alias, Table<TTouchOverviewRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("FAQ触达率数据统计表"));
    }

    public <O extends Record> TTouchOverview(Table<O> child, ForeignKey<O, TTouchOverviewRecord> key) {
        super(child, key, T_TOUCH_OVERVIEW);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Yibot.YIBOT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.T_TOUCH_OVERVIEW_IDX_DS_IT, Indexes.T_TOUCH_OVERVIEW_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TTouchOverviewRecord> getPrimaryKey() {
        return Keys.KEY_T_TOUCH_OVERVIEW_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TTouchOverviewRecord>> getKeys() {
        return Arrays.<UniqueKey<TTouchOverviewRecord>>asList(Keys.KEY_T_TOUCH_OVERVIEW_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TTouchOverview as(String alias) {
        return new TTouchOverview(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TTouchOverview as(Name alias) {
        return new TTouchOverview(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TTouchOverview rename(String name) {
        return new TTouchOverview(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TTouchOverview rename(Name name) {
        return new TTouchOverview(name, null);
    }
}
