/*
 * This file is generated by jOOQ.
 */
package com.zhuiyi.model.jooq.tables;


import com.zhuiyi.model.jooq.Indexes;
import com.zhuiyi.model.jooq.Keys;
import com.zhuiyi.model.jooq.Yibot;
import com.zhuiyi.model.jooq.tables.records.TWholeTrendOverviewRecord;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;

import javax.annotation.Generated;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;


/**
 * 整体趋势统计表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TWholeTrendOverview extends TableImpl<TWholeTrendOverviewRecord> {

    private static final long serialVersionUID = 1459170294;

    /**
     * The reference instance of <code>yibot.t_whole_trend_overview</code>
     */
    public static final TWholeTrendOverview T_WHOLE_TREND_OVERVIEW = new TWholeTrendOverview();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TWholeTrendOverviewRecord> getRecordType() {
        return TWholeTrendOverviewRecord.class;
    }

    /**
     * The column <code>yibot.t_whole_trend_overview.id</code>.
     */
    public final TableField<TWholeTrendOverviewRecord, ULong> ID = createField("id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>yibot.t_whole_trend_overview.appid</code>.
     */
    public final TableField<TWholeTrendOverviewRecord, String> APPID = createField("appid", org.jooq.impl.SQLDataType.VARCHAR(30).nullable(false), this, "");

    /**
     * The column <code>yibot.t_whole_trend_overview.date_sign</code>.
     */
    public final TableField<TWholeTrendOverviewRecord, String> DATE_SIGN = createField("date_sign", org.jooq.impl.SQLDataType.CHAR(10).nullable(false), this, "");

    /**
     * The column <code>yibot.t_whole_trend_overview.is_total</code>.
     */
    public final TableField<TWholeTrendOverviewRecord, Boolean> IS_TOTAL = createField("is_total", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>yibot.t_whole_trend_overview.cid</code>.
     */
    public final TableField<TWholeTrendOverviewRecord, String> CID = createField("cid", org.jooq.impl.SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>yibot.t_whole_trend_overview.client</code>.
     */
    public final TableField<TWholeTrendOverviewRecord, String> CLIENT = createField("client", org.jooq.impl.SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>yibot.t_whole_trend_overview.eid</code>.
     */
    public final TableField<TWholeTrendOverviewRecord, String> EID = createField("eid", org.jooq.impl.SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>yibot.t_whole_trend_overview.lables</code>.
     */
    public final TableField<TWholeTrendOverviewRecord, String> LABLES = createField("lables", org.jooq.impl.SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>yibot.t_whole_trend_overview.im</code>.
     */
    public final TableField<TWholeTrendOverviewRecord, String> IM = createField("im", org.jooq.impl.SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>yibot.t_whole_trend_overview.gmt_create</code>.
     */
    public final TableField<TWholeTrendOverviewRecord, Timestamp> GMT_CREATE = createField("gmt_create", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>yibot.t_whole_trend_overview.gmt_modified</code>.
     */
    public final TableField<TWholeTrendOverviewRecord, Timestamp> GMT_MODIFIED = createField("gmt_modified", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>yibot.t_whole_trend_overview.data</code>.
     */
    public final TableField<TWholeTrendOverviewRecord, String> DATA = createField("data", org.jooq.impl.SQLDataType.VARCHAR(4000).nullable(false), this, "");

    /**
     * Create a <code>yibot.t_whole_trend_overview</code> table reference
     */
    public TWholeTrendOverview() {
        this(DSL.name("t_whole_trend_overview"), null);
    }

    /**
     * Create an aliased <code>yibot.t_whole_trend_overview</code> table reference
     */
    public TWholeTrendOverview(String alias) {
        this(DSL.name(alias), T_WHOLE_TREND_OVERVIEW);
    }

    /**
     * Create an aliased <code>yibot.t_whole_trend_overview</code> table reference
     */
    public TWholeTrendOverview(Name alias) {
        this(alias, T_WHOLE_TREND_OVERVIEW);
    }

    private TWholeTrendOverview(Name alias, Table<TWholeTrendOverviewRecord> aliased) {
        this(alias, aliased, null);
    }

    private TWholeTrendOverview(Name alias, Table<TWholeTrendOverviewRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("整体趋势统计表"));
    }

    public <O extends Record> TWholeTrendOverview(Table<O> child, ForeignKey<O, TWholeTrendOverviewRecord> key) {
        super(child, key, T_WHOLE_TREND_OVERVIEW);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Yibot.YIBOT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.T_WHOLE_TREND_OVERVIEW_IDX_DS_IT, Indexes.T_WHOLE_TREND_OVERVIEW_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TWholeTrendOverviewRecord> getPrimaryKey() {
        return Keys.KEY_T_WHOLE_TREND_OVERVIEW_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TWholeTrendOverviewRecord>> getKeys() {
        return Arrays.<UniqueKey<TWholeTrendOverviewRecord>>asList(Keys.KEY_T_WHOLE_TREND_OVERVIEW_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TWholeTrendOverview as(String alias) {
        return new TWholeTrendOverview(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TWholeTrendOverview as(Name alias) {
        return new TWholeTrendOverview(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TWholeTrendOverview rename(String name) {
        return new TWholeTrendOverview(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TWholeTrendOverview rename(Name name) {
        return new TWholeTrendOverview(name, null);
    }
}
