/*
 * This file is generated by jOOQ.
 */
package com.zhuiyi.model.jooq.tables;


import com.zhuiyi.model.jooq.Indexes;
import com.zhuiyi.model.jooq.Keys;
import com.zhuiyi.model.jooq.Yibot;
import com.zhuiyi.model.jooq.tables.records.TZrgOverviewRecord;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;

import javax.annotation.Generated;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;


/**
 * 转人工数据统计表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TZrgOverview extends TableImpl<TZrgOverviewRecord> {

    private static final long serialVersionUID = -1389522677;

    /**
     * The reference instance of <code>yibot.t_zrg_overview</code>
     */
    public static final TZrgOverview T_ZRG_OVERVIEW = new TZrgOverview();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TZrgOverviewRecord> getRecordType() {
        return TZrgOverviewRecord.class;
    }

    /**
     * The column <code>yibot.t_zrg_overview.id</code>.
     */
    public final TableField<TZrgOverviewRecord, ULong> ID = createField("id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>yibot.t_zrg_overview.appid</code>.
     */
    public final TableField<TZrgOverviewRecord, String> APPID = createField("appid", org.jooq.impl.SQLDataType.VARCHAR(30).nullable(false), this, "");

    /**
     * The column <code>yibot.t_zrg_overview.date_sign</code>.
     */
    public final TableField<TZrgOverviewRecord, String> DATE_SIGN = createField("date_sign", org.jooq.impl.SQLDataType.CHAR(10).nullable(false), this, "");

    /**
     * The column <code>yibot.t_zrg_overview.is_total</code>.
     */
    public final TableField<TZrgOverviewRecord, Boolean> IS_TOTAL = createField("is_total", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>yibot.t_zrg_overview.cid</code>.
     */
    public final TableField<TZrgOverviewRecord, String> CID = createField("cid", org.jooq.impl.SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>yibot.t_zrg_overview.client</code>.
     */
    public final TableField<TZrgOverviewRecord, String> CLIENT = createField("client", org.jooq.impl.SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>yibot.t_zrg_overview.eid</code>.
     */
    public final TableField<TZrgOverviewRecord, String> EID = createField("eid", org.jooq.impl.SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>yibot.t_zrg_overview.lables</code>.
     */
    public final TableField<TZrgOverviewRecord, String> LABLES = createField("lables", org.jooq.impl.SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>yibot.t_zrg_overview.im</code>.
     */
    public final TableField<TZrgOverviewRecord, String> IM = createField("im", org.jooq.impl.SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>yibot.t_zrg_overview.gmt_create</code>.
     */
    public final TableField<TZrgOverviewRecord, Timestamp> GMT_CREATE = createField("gmt_create", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>yibot.t_zrg_overview.gmt_modified</code>.
     */
    public final TableField<TZrgOverviewRecord, Timestamp> GMT_MODIFIED = createField("gmt_modified", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>yibot.t_zrg_overview.data</code>.
     */
    public final TableField<TZrgOverviewRecord, String> DATA = createField("data", org.jooq.impl.SQLDataType.VARCHAR(4000).nullable(false), this, "");

    /**
     * Create a <code>yibot.t_zrg_overview</code> table reference
     */
    public TZrgOverview() {
        this(DSL.name("t_zrg_overview"), null);
    }

    /**
     * Create an aliased <code>yibot.t_zrg_overview</code> table reference
     */
    public TZrgOverview(String alias) {
        this(DSL.name(alias), T_ZRG_OVERVIEW);
    }

    /**
     * Create an aliased <code>yibot.t_zrg_overview</code> table reference
     */
    public TZrgOverview(Name alias) {
        this(alias, T_ZRG_OVERVIEW);
    }

    private TZrgOverview(Name alias, Table<TZrgOverviewRecord> aliased) {
        this(alias, aliased, null);
    }

    private TZrgOverview(Name alias, Table<TZrgOverviewRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("转人工数据统计表"));
    }

    public <O extends Record> TZrgOverview(Table<O> child, ForeignKey<O, TZrgOverviewRecord> key) {
        super(child, key, T_ZRG_OVERVIEW);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Yibot.YIBOT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.T_ZRG_OVERVIEW_IDX_DS_IT, Indexes.T_ZRG_OVERVIEW_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TZrgOverviewRecord> getPrimaryKey() {
        return Keys.KEY_T_ZRG_OVERVIEW_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TZrgOverviewRecord>> getKeys() {
        return Arrays.<UniqueKey<TZrgOverviewRecord>>asList(Keys.KEY_T_ZRG_OVERVIEW_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TZrgOverview as(String alias) {
        return new TZrgOverview(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TZrgOverview as(Name alias) {
        return new TZrgOverview(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TZrgOverview rename(String name) {
        return new TZrgOverview(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TZrgOverview rename(Name name) {
        return new TZrgOverview(name, null);
    }
}
