/*
 * This file is generated by jOOQ.
 */
package com.zhuiyi.model.jooq.routines;


import com.zhuiyi.model.jooq.Yibot;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TestInsert extends AbstractRoutine<Void> {

    private static final long serialVersionUID = 48088085;

    /**
     * The parameter <code>yibot.test_insert.c_num</code>.
     */
    public static final Parameter<Integer> C_NUM = createParameter("c_num", org.jooq.impl.SQLDataType.INTEGER, false, false);

    /**
     * Create a new routine call instance
     */
    public TestInsert() {
        super("test_insert", Yibot.YIBOT);

        addInParameter(C_NUM);
    }

    /**
     * Set the <code>c_num</code> parameter IN value to the routine
     */
    public void setCNum(Integer value) {
        setValue(C_NUM, value);
    }
}
