/*
 * This file is generated by jOOQ.
 */
package com.zhuiyi.model.jooq.tables.records;


import com.zhuiyi.model.jooq.tables.TDialogDetail;
import org.jooq.Record4;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;


/**
 * 机器对话流水明细表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TDialogDetailRecord extends UpdatableRecordImpl<TDialogDetailRecord> {

    private static final long serialVersionUID = 1050942804;

    /**
     * Setter for <code>yibot.t_dialog_detail.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>yibot.t_dialog_detail.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>yibot.t_dialog_detail.appid</code>.
     */
    public void setAppid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>yibot.t_dialog_detail.appid</code>.
     */
    public String getAppid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>yibot.t_dialog_detail.date_month</code>.
     */
    public void setDateMonth(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>yibot.t_dialog_detail.date_month</code>.
     */
    public String getDateMonth() {
        return (String) get(2);
    }

    /**
     * Setter for <code>yibot.t_dialog_detail.exact_time</code>.
     */
    public void setExactTime(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>yibot.t_dialog_detail.exact_time</code>.
     */
    public Timestamp getExactTime() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>yibot.t_dialog_detail.recv_time</code>.
     */
    public void setRecvTime(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>yibot.t_dialog_detail.recv_time</code>.
     */
    public Timestamp getRecvTime() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>yibot.t_dialog_detail.retmsg</code>.
     */
    public void setRetmsg(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>yibot.t_dialog_detail.retmsg</code>.
     */
    public String getRetmsg() {
        return (String) get(5);
    }

    /**
     * Setter for <code>yibot.t_dialog_detail.direct_faq_id</code>.
     */
    public void setDirectFaqId(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>yibot.t_dialog_detail.direct_faq_id</code>.
     */
    public String getDirectFaqId() {
        return (String) get(6);
    }

    /**
     * Setter for <code>yibot.t_dialog_detail.indirect_faq_id</code>.
     */
    public void setIndirectFaqId(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>yibot.t_dialog_detail.indirect_faq_id</code>.
     */
    public String getIndirectFaqId() {
        return (String) get(7);
    }

    /**
     * Setter for <code>yibot.t_dialog_detail.direct_faq</code>.
     */
    public void setDirectFaq(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>yibot.t_dialog_detail.direct_faq</code>.
     */
    public String getDirectFaq() {
        return (String) get(8);
    }

    /**
     * Setter for <code>yibot.t_dialog_detail.indirect_faq</code>.
     */
    public void setIndirectFaq(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>yibot.t_dialog_detail.indirect_faq</code>.
     */
    public String getIndirectFaq() {
        return (String) get(9);
    }

    /**
     * Setter for <code>yibot.t_dialog_detail.user_ip</code>.
     */
    public void setUserIp(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>yibot.t_dialog_detail.user_ip</code>.
     */
    public String getUserIp() {
        return (String) get(10);
    }

    /**
     * Setter for <code>yibot.t_dialog_detail.query</code>.
     */
    public void setQuery(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>yibot.t_dialog_detail.query</code>.
     */
    public String getQuery() {
        return (String) get(11);
    }

    /**
     * Setter for <code>yibot.t_dialog_detail.answer</code>.
     */
    public void setAnswer(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>yibot.t_dialog_detail.answer</code>.
     */
    public String getAnswer() {
        return (String) get(12);
    }

    /**
     * Setter for <code>yibot.t_dialog_detail.biz_portal</code>.
     */
    public void setBizPortal(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>yibot.t_dialog_detail.biz_portal</code>.
     */
    public String getBizPortal() {
        return (String) get(13);
    }

    /**
     * Setter for <code>yibot.t_dialog_detail.biz_ret_code</code>.
     */
    public void setBizRetCode(Boolean value) {
        set(14, value);
    }

    /**
     * Getter for <code>yibot.t_dialog_detail.biz_ret_code</code>.
     */
    public Boolean getBizRetCode() {
        return (Boolean) get(14);
    }

    /**
     * Setter for <code>yibot.t_dialog_detail.biz_docid</code>.
     */
    public void setBizDocid(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>yibot.t_dialog_detail.biz_docid</code>.
     */
    public String getBizDocid() {
        return (String) get(15);
    }

    /**
     * Setter for <code>yibot.t_dialog_detail.biz_ret_str</code>.
     */
    public void setBizRetStr(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>yibot.t_dialog_detail.biz_ret_str</code>.
     */
    public String getBizRetStr() {
        return (String) get(16);
    }

    /**
     * Setter for <code>yibot.t_dialog_detail.ccd_cost</code>.
     */
    public void setCcdCost(Integer value) {
        set(17, value);
    }

    /**
     * Getter for <code>yibot.t_dialog_detail.ccd_cost</code>.
     */
    public Integer getCcdCost() {
        return (Integer) get(17);
    }

    /**
     * Setter for <code>yibot.t_dialog_detail.x_forward</code>.
     */
    public void setXForward(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>yibot.t_dialog_detail.x_forward</code>.
     */
    public String getXForward() {
        return (String) get(18);
    }

    /**
     * Setter for <code>yibot.t_dialog_detail.biz_cost</code>.
     */
    public void setBizCost(Integer value) {
        set(19, value);
    }

    /**
     * Getter for <code>yibot.t_dialog_detail.biz_cost</code>.
     */
    public Integer getBizCost() {
        return (Integer) get(19);
    }

    /**
     * Setter for <code>yibot.t_dialog_detail.answer_index</code>.
     */
    public void setAnswerIndex(String value) {
        set(20, value);
    }

    /**
     * Getter for <code>yibot.t_dialog_detail.answer_index</code>.
     */
    public String getAnswerIndex() {
        return (String) get(20);
    }

    /**
     * Setter for <code>yibot.t_dialog_detail.place</code>.
     */
    public void setPlace(String value) {
        set(21, value);
    }

    /**
     * Getter for <code>yibot.t_dialog_detail.place</code>.
     */
    public String getPlace() {
        return (String) get(21);
    }

    /**
     * Setter for <code>yibot.t_dialog_detail.other</code>.
     */
    public void setOther(String value) {
        set(22, value);
    }

    /**
     * Getter for <code>yibot.t_dialog_detail.other</code>.
     */
    public String getOther() {
        return (String) get(22);
    }

    /**
     * Setter for <code>yibot.t_dialog_detail.sen_level</code>.
     */
    public void setSenLevel(Boolean value) {
        set(23, value);
    }

    /**
     * Getter for <code>yibot.t_dialog_detail.sen_level</code>.
     */
    public Boolean getSenLevel() {
        return (Boolean) get(23);
    }

    /**
     * Setter for <code>yibot.t_dialog_detail.sen_words</code>.
     */
    public void setSenWords(String value) {
        set(24, value);
    }

    /**
     * Getter for <code>yibot.t_dialog_detail.sen_words</code>.
     */
    public String getSenWords() {
        return (String) get(24);
    }

    /**
     * Setter for <code>yibot.t_dialog_detail.confidence</code>.
     */
    public void setConfidence(String value) {
        set(25, value);
    }

    /**
     * Getter for <code>yibot.t_dialog_detail.confidence</code>.
     */
    public String getConfidence() {
        return (String) get(25);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record4<String, String, Timestamp, String> key() {
        return (Record4) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TDialogDetailRecord
     */
    public TDialogDetailRecord() {
        super(TDialogDetail.T_DIALOG_DETAIL);
    }

    /**
     * Create a detached, initialised TDialogDetailRecord
     */
    public TDialogDetailRecord(String id, String appid, String dateMonth, Timestamp exactTime, Timestamp recvTime, String retmsg, String directFaqId, String indirectFaqId, String directFaq, String indirectFaq, String userIp, String query, String answer, String bizPortal, Boolean bizRetCode, String bizDocid, String bizRetStr, Integer ccdCost, String xForward, Integer bizCost, String answerIndex, String place, String other, Boolean senLevel, String senWords, String confidence) {
        super(TDialogDetail.T_DIALOG_DETAIL);

        set(0, id);
        set(1, appid);
        set(2, dateMonth);
        set(3, exactTime);
        set(4, recvTime);
        set(5, retmsg);
        set(6, directFaqId);
        set(7, indirectFaqId);
        set(8, directFaq);
        set(9, indirectFaq);
        set(10, userIp);
        set(11, query);
        set(12, answer);
        set(13, bizPortal);
        set(14, bizRetCode);
        set(15, bizDocid);
        set(16, bizRetStr);
        set(17, ccdCost);
        set(18, xForward);
        set(19, bizCost);
        set(20, answerIndex);
        set(21, place);
        set(22, other);
        set(23, senLevel);
        set(24, senWords);
        set(25, confidence);
    }
}
