/*
 * This file is generated by jOOQ.
 */
package com.zhuiyi.model.jooq.tables.records;


import com.zhuiyi.model.jooq.tables.TFaqTouchOverview;
import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;

import javax.annotation.Generated;
import java.sql.Timestamp;


/**
 * faq触达数据统计表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TFaqTouchOverviewRecord extends UpdatableRecordImpl<TFaqTouchOverviewRecord> {

    private static final long serialVersionUID = -443839221;

    /**
     * Setter for <code>yibot.t_faq_touch_overview.id</code>.
     */
    public void setId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>yibot.t_faq_touch_overview.id</code>.
     */
    public ULong getId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>yibot.t_faq_touch_overview.appid</code>.
     */
    public void setAppid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>yibot.t_faq_touch_overview.appid</code>.
     */
    public String getAppid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>yibot.t_faq_touch_overview.date_sign</code>.
     */
    public void setDateSign(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>yibot.t_faq_touch_overview.date_sign</code>.
     */
    public String getDateSign() {
        return (String) get(2);
    }

    /**
     * Setter for <code>yibot.t_faq_touch_overview.faq_id</code>.
     */
    public void setFaqId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>yibot.t_faq_touch_overview.faq_id</code>.
     */
    public Integer getFaqId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>yibot.t_faq_touch_overview.faq</code>.
     */
    public void setFaq(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>yibot.t_faq_touch_overview.faq</code>.
     */
    public String getFaq() {
        return (String) get(4);
    }

    /**
     * Setter for <code>yibot.t_faq_touch_overview.category_id</code>.
     */
    public void setCategoryId(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>yibot.t_faq_touch_overview.category_id</code>.
     */
    public String getCategoryId() {
        return (String) get(5);
    }

    /**
     * Setter for <code>yibot.t_faq_touch_overview.touch_num</code>.
     */
    public void setTouchNum(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>yibot.t_faq_touch_overview.touch_num</code>.
     */
    public Integer getTouchNum() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>yibot.t_faq_touch_overview.direct_num</code>.
     */
    public void setDirectNum(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>yibot.t_faq_touch_overview.direct_num</code>.
     */
    public Integer getDirectNum() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>yibot.t_faq_touch_overview.recommend_num</code>.
     */
    public void setRecommendNum(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>yibot.t_faq_touch_overview.recommend_num</code>.
     */
    public Integer getRecommendNum() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>yibot.t_faq_touch_overview.recommend_ans_num</code>.
     */
    public void setRecommendAnsNum(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>yibot.t_faq_touch_overview.recommend_ans_num</code>.
     */
    public Integer getRecommendAnsNum() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>yibot.t_faq_touch_overview.click_good</code>.
     */
    public void setClickGood(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>yibot.t_faq_touch_overview.click_good</code>.
     */
    public Integer getClickGood() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>yibot.t_faq_touch_overview.click_bad</code>.
     */
    public void setClickBad(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>yibot.t_faq_touch_overview.click_bad</code>.
     */
    public Integer getClickBad() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>yibot.t_faq_touch_overview.touch_rate</code>.
     */
    public void setTouchRate(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>yibot.t_faq_touch_overview.touch_rate</code>.
     */
    public String getTouchRate() {
        return (String) get(12);
    }

    /**
     * Setter for <code>yibot.t_faq_touch_overview.zd_zrg</code>.
     */
    public void setZdZrg(Integer value) {
        set(13, value);
    }

    /**
     * Getter for <code>yibot.t_faq_touch_overview.zd_zrg</code>.
     */
    public Integer getZdZrg() {
        return (Integer) get(13);
    }

    /**
     * Setter for <code>yibot.t_faq_touch_overview.bd_zrg</code>.
     */
    public void setBdZrg(Integer value) {
        set(14, value);
    }

    /**
     * Getter for <code>yibot.t_faq_touch_overview.bd_zrg</code>.
     */
    public Integer getBdZrg() {
        return (Integer) get(14);
    }

    /**
     * Setter for <code>yibot.t_faq_touch_overview.total_zrg</code>.
     */
    public void setTotalZrg(Integer value) {
        set(15, value);
    }

    /**
     * Getter for <code>yibot.t_faq_touch_overview.total_zrg</code>.
     */
    public Integer getTotalZrg() {
        return (Integer) get(15);
    }

    /**
     * Setter for <code>yibot.t_faq_touch_overview.click_good_rate</code>.
     */
    public void setClickGoodRate(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>yibot.t_faq_touch_overview.click_good_rate</code>.
     */
    public String getClickGoodRate() {
        return (String) get(16);
    }

    /**
     * Setter for <code>yibot.t_faq_touch_overview.click_bad_rate</code>.
     */
    public void setClickBadRate(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>yibot.t_faq_touch_overview.click_bad_rate</code>.
     */
    public String getClickBadRate() {
        return (String) get(17);
    }

    /**
     * Setter for <code>yibot.t_faq_touch_overview.biz_type</code>.
     */
    public void setBizType(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>yibot.t_faq_touch_overview.biz_type</code>.
     */
    public String getBizType() {
        return (String) get(18);
    }

    /**
     * Setter for <code>yibot.t_faq_touch_overview.total_click</code>.
     */
    public void setTotalClick(Integer value) {
        set(19, value);
    }

    /**
     * Getter for <code>yibot.t_faq_touch_overview.total_click</code>.
     */
    public Integer getTotalClick() {
        return (Integer) get(19);
    }

    /**
     * Setter for <code>yibot.t_faq_touch_overview.zrg_rate</code>.
     */
    public void setZrgRate(String value) {
        set(20, value);
    }

    /**
     * Getter for <code>yibot.t_faq_touch_overview.zrg_rate</code>.
     */
    public String getZrgRate() {
        return (String) get(20);
    }

    /**
     * Setter for <code>yibot.t_faq_touch_overview.labels</code>.
     */
    public void setLabels(String value) {
        set(21, value);
    }

    /**
     * Getter for <code>yibot.t_faq_touch_overview.labels</code>.
     */
    public String getLabels() {
        return (String) get(21);
    }

    /**
     * Setter for <code>yibot.t_faq_touch_overview.gmt_create</code>.
     */
    public void setGmtCreate(Timestamp value) {
        set(22, value);
    }

    /**
     * Getter for <code>yibot.t_faq_touch_overview.gmt_create</code>.
     */
    public Timestamp getGmtCreate() {
        return (Timestamp) get(22);
    }

    /**
     * Setter for <code>yibot.t_faq_touch_overview.gmt_modified</code>.
     */
    public void setGmtModified(Timestamp value) {
        set(23, value);
    }

    /**
     * Getter for <code>yibot.t_faq_touch_overview.gmt_modified</code>.
     */
    public Timestamp getGmtModified() {
        return (Timestamp) get(23);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<ULong, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TFaqTouchOverviewRecord
     */
    public TFaqTouchOverviewRecord() {
        super(TFaqTouchOverview.T_FAQ_TOUCH_OVERVIEW);
    }

    /**
     * Create a detached, initialised TFaqTouchOverviewRecord
     */
    public TFaqTouchOverviewRecord(ULong id, String appid, String dateSign, Integer faqId, String faq, String categoryId, Integer touchNum, Integer directNum, Integer recommendNum, Integer recommendAnsNum, Integer clickGood, Integer clickBad, String touchRate, Integer zdZrg, Integer bdZrg, Integer totalZrg, String clickGoodRate, String clickBadRate, String bizType, Integer totalClick, String zrgRate, String labels, Timestamp gmtCreate, Timestamp gmtModified) {
        super(TFaqTouchOverview.T_FAQ_TOUCH_OVERVIEW);

        set(0, id);
        set(1, appid);
        set(2, dateSign);
        set(3, faqId);
        set(4, faq);
        set(5, categoryId);
        set(6, touchNum);
        set(7, directNum);
        set(8, recommendNum);
        set(9, recommendAnsNum);
        set(10, clickGood);
        set(11, clickBad);
        set(12, touchRate);
        set(13, zdZrg);
        set(14, bdZrg);
        set(15, totalZrg);
        set(16, clickGoodRate);
        set(17, clickBadRate);
        set(18, bizType);
        set(19, totalClick);
        set(20, zrgRate);
        set(21, labels);
        set(22, gmtCreate);
        set(23, gmtModified);
    }
}
