/*
 * This file is generated by jOOQ.
 */
package com.zhuiyi.model.jooq.tables.records;


import com.zhuiyi.model.jooq.tables.THotAreaFqOverview;
import org.jooq.Field;
import org.jooq.Record11;
import org.jooq.Record2;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;

import javax.annotation.Generated;
import java.sql.Timestamp;


/**
 * 热点区域FAQ数据统计表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class THotAreaFqOverviewRecord extends UpdatableRecordImpl<THotAreaFqOverviewRecord> implements Record11<ULong, String, String, Boolean, String, Integer, String, Integer, String, Timestamp, Timestamp> {

    private static final long serialVersionUID = 1689319027;

    /**
     * Setter for <code>yibot.t_hot_area_fq_overview.id</code>.
     */
    public void setId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>yibot.t_hot_area_fq_overview.id</code>.
     */
    public ULong getId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>yibot.t_hot_area_fq_overview.appid</code>.
     */
    public void setAppid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>yibot.t_hot_area_fq_overview.appid</code>.
     */
    public String getAppid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>yibot.t_hot_area_fq_overview.date_sign</code>.
     */
    public void setDateSign(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>yibot.t_hot_area_fq_overview.date_sign</code>.
     */
    public String getDateSign() {
        return (String) get(2);
    }

    /**
     * Setter for <code>yibot.t_hot_area_fq_overview.area_type</code>.
     */
    public void setAreaType(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>yibot.t_hot_area_fq_overview.area_type</code>.
     */
    public Boolean getAreaType() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>yibot.t_hot_area_fq_overview.area_name</code>.
     */
    public void setAreaName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>yibot.t_hot_area_fq_overview.area_name</code>.
     */
    public String getAreaName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>yibot.t_hot_area_fq_overview.faq_id</code>.
     */
    public void setFaqId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>yibot.t_hot_area_fq_overview.faq_id</code>.
     */
    public Integer getFaqId() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>yibot.t_hot_area_fq_overview.faq</code>.
     */
    public void setFaq(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>yibot.t_hot_area_fq_overview.faq</code>.
     */
    public String getFaq() {
        return (String) get(6);
    }

    /**
     * Setter for <code>yibot.t_hot_area_fq_overview.visit_num</code>.
     */
    public void setVisitNum(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>yibot.t_hot_area_fq_overview.visit_num</code>.
     */
    public Integer getVisitNum() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>yibot.t_hot_area_fq_overview.visit_trend</code>.
     */
    public void setVisitTrend(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>yibot.t_hot_area_fq_overview.visit_trend</code>.
     */
    public String getVisitTrend() {
        return (String) get(8);
    }

    /**
     * Setter for <code>yibot.t_hot_area_fq_overview.gmt_create</code>.
     */
    public void setGmtCreate(Timestamp value) {
        set(9, value);
    }

    /**
     * Getter for <code>yibot.t_hot_area_fq_overview.gmt_create</code>.
     */
    public Timestamp getGmtCreate() {
        return (Timestamp) get(9);
    }

    /**
     * Setter for <code>yibot.t_hot_area_fq_overview.gmt_modified</code>.
     */
    public void setGmtModified(Timestamp value) {
        set(10, value);
    }

    /**
     * Getter for <code>yibot.t_hot_area_fq_overview.gmt_modified</code>.
     */
    public Timestamp getGmtModified() {
        return (Timestamp) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<ULong, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<ULong, String, String, Boolean, String, Integer, String, Integer, String, Timestamp, Timestamp> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<ULong, String, String, Boolean, String, Integer, String, Integer, String, Timestamp, Timestamp> valuesRow() {
        return (Row11) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field1() {
        return THotAreaFqOverview.T_HOT_AREA_FQ_OVERVIEW.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return THotAreaFqOverview.T_HOT_AREA_FQ_OVERVIEW.APPID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return THotAreaFqOverview.T_HOT_AREA_FQ_OVERVIEW.DATE_SIGN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field4() {
        return THotAreaFqOverview.T_HOT_AREA_FQ_OVERVIEW.AREA_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return THotAreaFqOverview.T_HOT_AREA_FQ_OVERVIEW.AREA_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return THotAreaFqOverview.T_HOT_AREA_FQ_OVERVIEW.FAQ_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return THotAreaFqOverview.T_HOT_AREA_FQ_OVERVIEW.FAQ;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return THotAreaFqOverview.T_HOT_AREA_FQ_OVERVIEW.VISIT_NUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return THotAreaFqOverview.T_HOT_AREA_FQ_OVERVIEW.VISIT_TREND;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field10() {
        return THotAreaFqOverview.T_HOT_AREA_FQ_OVERVIEW.GMT_CREATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field11() {
        return THotAreaFqOverview.T_HOT_AREA_FQ_OVERVIEW.GMT_MODIFIED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getAppid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getDateSign();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component4() {
        return getAreaType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getAreaName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getFaqId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getFaq();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getVisitNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getVisitTrend();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component10() {
        return getGmtCreate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component11() {
        return getGmtModified();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getAppid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getDateSign();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value4() {
        return getAreaType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getAreaName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getFaqId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getFaq();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getVisitNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getVisitTrend();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value10() {
        return getGmtCreate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value11() {
        return getGmtModified();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public THotAreaFqOverviewRecord value1(ULong value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public THotAreaFqOverviewRecord value2(String value) {
        setAppid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public THotAreaFqOverviewRecord value3(String value) {
        setDateSign(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public THotAreaFqOverviewRecord value4(Boolean value) {
        setAreaType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public THotAreaFqOverviewRecord value5(String value) {
        setAreaName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public THotAreaFqOverviewRecord value6(Integer value) {
        setFaqId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public THotAreaFqOverviewRecord value7(String value) {
        setFaq(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public THotAreaFqOverviewRecord value8(Integer value) {
        setVisitNum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public THotAreaFqOverviewRecord value9(String value) {
        setVisitTrend(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public THotAreaFqOverviewRecord value10(Timestamp value) {
        setGmtCreate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public THotAreaFqOverviewRecord value11(Timestamp value) {
        setGmtModified(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public THotAreaFqOverviewRecord values(ULong value1, String value2, String value3, Boolean value4, String value5, Integer value6, String value7, Integer value8, String value9, Timestamp value10, Timestamp value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached THotAreaFqOverviewRecord
     */
    public THotAreaFqOverviewRecord() {
        super(THotAreaFqOverview.T_HOT_AREA_FQ_OVERVIEW);
    }

    /**
     * Create a detached, initialised THotAreaFqOverviewRecord
     */
    public THotAreaFqOverviewRecord(ULong id, String appid, String dateSign, Boolean areaType, String areaName, Integer faqId, String faq, Integer visitNum, String visitTrend, Timestamp gmtCreate, Timestamp gmtModified) {
        super(THotAreaFqOverview.T_HOT_AREA_FQ_OVERVIEW);

        set(0, id);
        set(1, appid);
        set(2, dateSign);
        set(3, areaType);
        set(4, areaName);
        set(5, faqId);
        set(6, faq);
        set(7, visitNum);
        set(8, visitTrend);
        set(9, gmtCreate);
        set(10, gmtModified);
    }
}
