/*
 * This file is generated by jOOQ.
 */
package com.zhuiyi.model.jooq.tables.records;


import com.zhuiyi.model.jooq.tables.TZrgOverview;
import org.jooq.Field;
import org.jooq.Record12;
import org.jooq.Record2;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;

import javax.annotation.Generated;
import java.sql.Timestamp;


/**
 * 转人工数据统计表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TZrgOverviewRecord extends UpdatableRecordImpl<TZrgOverviewRecord> implements Record12<ULong, String, String, Boolean, String, String, String, String, String, Timestamp, Timestamp, String> {

    private static final long serialVersionUID = -371895976;

    /**
     * Setter for <code>yibot.t_zrg_overview.id</code>.
     */
    public void setId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>yibot.t_zrg_overview.id</code>.
     */
    public ULong getId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>yibot.t_zrg_overview.appid</code>.
     */
    public void setAppid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>yibot.t_zrg_overview.appid</code>.
     */
    public String getAppid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>yibot.t_zrg_overview.date_sign</code>.
     */
    public void setDateSign(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>yibot.t_zrg_overview.date_sign</code>.
     */
    public String getDateSign() {
        return (String) get(2);
    }

    /**
     * Setter for <code>yibot.t_zrg_overview.is_total</code>.
     */
    public void setIsTotal(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>yibot.t_zrg_overview.is_total</code>.
     */
    public Boolean getIsTotal() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>yibot.t_zrg_overview.cid</code>.
     */
    public void setCid(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>yibot.t_zrg_overview.cid</code>.
     */
    public String getCid() {
        return (String) get(4);
    }

    /**
     * Setter for <code>yibot.t_zrg_overview.client</code>.
     */
    public void setClient(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>yibot.t_zrg_overview.client</code>.
     */
    public String getClient() {
        return (String) get(5);
    }

    /**
     * Setter for <code>yibot.t_zrg_overview.eid</code>.
     */
    public void setEid(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>yibot.t_zrg_overview.eid</code>.
     */
    public String getEid() {
        return (String) get(6);
    }

    /**
     * Setter for <code>yibot.t_zrg_overview.lables</code>.
     */
    public void setLables(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>yibot.t_zrg_overview.lables</code>.
     */
    public String getLables() {
        return (String) get(7);
    }

    /**
     * Setter for <code>yibot.t_zrg_overview.im</code>.
     */
    public void setIm(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>yibot.t_zrg_overview.im</code>.
     */
    public String getIm() {
        return (String) get(8);
    }

    /**
     * Setter for <code>yibot.t_zrg_overview.gmt_create</code>.
     */
    public void setGmtCreate(Timestamp value) {
        set(9, value);
    }

    /**
     * Getter for <code>yibot.t_zrg_overview.gmt_create</code>.
     */
    public Timestamp getGmtCreate() {
        return (Timestamp) get(9);
    }

    /**
     * Setter for <code>yibot.t_zrg_overview.gmt_modified</code>.
     */
    public void setGmtModified(Timestamp value) {
        set(10, value);
    }

    /**
     * Getter for <code>yibot.t_zrg_overview.gmt_modified</code>.
     */
    public Timestamp getGmtModified() {
        return (Timestamp) get(10);
    }

    /**
     * Setter for <code>yibot.t_zrg_overview.data</code>.
     */
    public void setData(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>yibot.t_zrg_overview.data</code>.
     */
    public String getData() {
        return (String) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<ULong, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<ULong, String, String, Boolean, String, String, String, String, String, Timestamp, Timestamp, String> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<ULong, String, String, Boolean, String, String, String, String, String, Timestamp, Timestamp, String> valuesRow() {
        return (Row12) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field1() {
        return TZrgOverview.T_ZRG_OVERVIEW.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TZrgOverview.T_ZRG_OVERVIEW.APPID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TZrgOverview.T_ZRG_OVERVIEW.DATE_SIGN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field4() {
        return TZrgOverview.T_ZRG_OVERVIEW.IS_TOTAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TZrgOverview.T_ZRG_OVERVIEW.CID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return TZrgOverview.T_ZRG_OVERVIEW.CLIENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return TZrgOverview.T_ZRG_OVERVIEW.EID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return TZrgOverview.T_ZRG_OVERVIEW.LABLES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return TZrgOverview.T_ZRG_OVERVIEW.IM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field10() {
        return TZrgOverview.T_ZRG_OVERVIEW.GMT_CREATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field11() {
        return TZrgOverview.T_ZRG_OVERVIEW.GMT_MODIFIED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return TZrgOverview.T_ZRG_OVERVIEW.DATA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getAppid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getDateSign();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component4() {
        return getIsTotal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getCid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getClient();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getEid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getLables();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getIm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component10() {
        return getGmtCreate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component11() {
        return getGmtModified();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getData();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getAppid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getDateSign();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value4() {
        return getIsTotal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getCid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getClient();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getEid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getLables();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getIm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value10() {
        return getGmtCreate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value11() {
        return getGmtModified();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getData();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TZrgOverviewRecord value1(ULong value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TZrgOverviewRecord value2(String value) {
        setAppid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TZrgOverviewRecord value3(String value) {
        setDateSign(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TZrgOverviewRecord value4(Boolean value) {
        setIsTotal(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TZrgOverviewRecord value5(String value) {
        setCid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TZrgOverviewRecord value6(String value) {
        setClient(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TZrgOverviewRecord value7(String value) {
        setEid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TZrgOverviewRecord value8(String value) {
        setLables(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TZrgOverviewRecord value9(String value) {
        setIm(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TZrgOverviewRecord value10(Timestamp value) {
        setGmtCreate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TZrgOverviewRecord value11(Timestamp value) {
        setGmtModified(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TZrgOverviewRecord value12(String value) {
        setData(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TZrgOverviewRecord values(ULong value1, String value2, String value3, Boolean value4, String value5, String value6, String value7, String value8, String value9, Timestamp value10, Timestamp value11, String value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TZrgOverviewRecord
     */
    public TZrgOverviewRecord() {
        super(TZrgOverview.T_ZRG_OVERVIEW);
    }

    /**
     * Create a detached, initialised TZrgOverviewRecord
     */
    public TZrgOverviewRecord(ULong id, String appid, String dateSign, Boolean isTotal, String cid, String client, String eid, String lables, String im, Timestamp gmtCreate, Timestamp gmtModified, String data) {
        super(TZrgOverview.T_ZRG_OVERVIEW);

        set(0, id);
        set(1, appid);
        set(2, dateSign);
        set(3, isTotal);
        set(4, cid);
        set(5, client);
        set(6, eid);
        set(7, lables);
        set(8, im);
        set(9, gmtCreate);
        set(10, gmtModified);
        set(11, data);
    }
}
